# База продуктов питания (калории на 100г)
# Формат: name_ru, name_en, name_uk, name_kk, calories, protein, fat, carbs, category

FOODS = [
    # === ФРУКТЫ ===
    {"name_ru": "Абрикос", "name_en": "Apricot", "name_uk": "Абрикос", "name_kk": "Өрік", "calories": 44, "protein": 0.9, "fat": 0.1, "carbs": 9.0, "category": "fruits"},
    {"name_ru": "Авокадо", "name_en": "Avocado", "name_uk": "Авокадо", "name_kk": "Авокадо", "calories": 160, "protein": 2.0, "fat": 15.0, "carbs": 9.0, "category": "fruits"},
    {"name_ru": "Ананас", "name_en": "Pineapple", "name_uk": "Ананас", "name_kk": "Ананас", "calories": 50, "protein": 0.5, "fat": 0.1, "carbs": 13.0, "category": "fruits"},
    {"name_ru": "Апельсин", "name_en": "Orange", "name_uk": "Апельсин", "name_kk": "Апельсин", "calories": 43, "protein": 0.9, "fat": 0.2, "carbs": 8.1, "category": "fruits"},
    {"name_ru": "Арбуз", "name_en": "Watermelon", "name_uk": "Кавун", "name_kk": "Қарбыз", "calories": 30, "protein": 0.6, "fat": 0.1, "carbs": 7.5, "category": "fruits"},
    {"name_ru": "Банан", "name_en": "Banana", "name_uk": "Банан", "name_kk": "Банан", "calories": 89, "protein": 1.1, "fat": 0.3, "carbs": 22.8, "category": "fruits"},
    {"name_ru": "Виноград", "name_en": "Grapes", "name_uk": "Виноград", "name_kk": "Жүзім", "calories": 67, "protein": 0.6, "fat": 0.2, "carbs": 17.2, "category": "fruits"},
    {"name_ru": "Вишня", "name_en": "Cherry", "name_uk": "Вишня", "name_kk": "Шие", "calories": 52, "protein": 0.8, "fat": 0.5, "carbs": 10.6, "category": "fruits"},
    {"name_ru": "Груша", "name_en": "Pear", "name_uk": "Груша", "name_kk": "Алмұрт", "calories": 57, "protein": 0.4, "fat": 0.3, "carbs": 15.2, "category": "fruits"},
    {"name_ru": "Дыня", "name_en": "Melon", "name_uk": "Диня", "name_kk": "Қауын", "calories": 34, "protein": 0.6, "fat": 0.3, "carbs": 7.4, "category": "fruits"},
    {"name_ru": "Киви", "name_en": "Kiwi", "name_uk": "Ківі", "name_kk": "Киви", "calories": 61, "protein": 1.1, "fat": 0.5, "carbs": 14.7, "category": "fruits"},
    {"name_ru": "Клубника", "name_en": "Strawberry", "name_uk": "Полуниця", "name_kk": "Құлпынай", "calories": 30, "protein": 0.8, "fat": 0.4, "carbs": 5.5, "category": "fruits"},
    {"name_ru": "Лимон", "name_en": "Lemon", "name_uk": "Лимон", "name_kk": "Лимон", "calories": 29, "protein": 1.1, "fat": 0.3, "carbs": 3.0, "category": "fruits"},
    {"name_ru": "Малина", "name_en": "Raspberry", "name_uk": "Малина", "name_kk": "Таңқурай", "calories": 46, "protein": 0.8, "fat": 0.5, "carbs": 8.3, "category": "fruits"},
    {"name_ru": "Манго", "name_en": "Mango", "name_uk": "Манго", "name_kk": "Манго", "calories": 60, "protein": 0.8, "fat": 0.4, "carbs": 14.8, "category": "fruits"},
    {"name_ru": "Мандарин", "name_en": "Tangerine", "name_uk": "Мандарин", "name_kk": "Мандарин", "calories": 38, "protein": 0.8, "fat": 0.2, "carbs": 7.5, "category": "fruits"},
    {"name_ru": "Персик", "name_en": "Peach", "name_uk": "Персик", "name_kk": "Шабдалы", "calories": 39, "protein": 0.9, "fat": 0.1, "carbs": 9.5, "category": "fruits"},
    {"name_ru": "Слива", "name_en": "Plum", "name_uk": "Слива", "name_kk": "Өрік", "calories": 46, "protein": 0.7, "fat": 0.3, "carbs": 9.6, "category": "fruits"},
    {"name_ru": "Черника", "name_en": "Blueberry", "name_uk": "Чорниця", "name_kk": "Көкжидек", "calories": 57, "protein": 0.7, "fat": 0.3, "carbs": 14.5, "category": "fruits"},
    {"name_ru": "Яблоко", "name_en": "Apple", "name_uk": "Яблуко", "name_kk": "Алма", "calories": 52, "protein": 0.3, "fat": 0.2, "carbs": 14.0, "category": "fruits"},
    {"name_ru": "Гранат", "name_en": "Pomegranate", "name_uk": "Гранат", "name_kk": "Анар", "calories": 83, "protein": 1.7, "fat": 1.2, "carbs": 18.7, "category": "fruits"},
    {"name_ru": "Папайя", "name_en": "Papaya", "name_uk": "Папайя", "name_kk": "Папайя", "calories": 39, "protein": 0.6, "fat": 0.1, "carbs": 9.8, "category": "fruits"},

    # === ОВОЩИ ===
    {"name_ru": "Баклажан", "name_en": "Eggplant", "name_uk": "Баклажан", "name_kk": "Баклажан", "calories": 24, "protein": 1.2, "fat": 0.1, "carbs": 5.5, "category": "vegetables"},
    {"name_ru": "Брокколи", "name_en": "Broccoli", "name_uk": "Броколі", "name_kk": "Брокколи", "calories": 34, "protein": 2.8, "fat": 0.4, "carbs": 7.0, "category": "vegetables"},
    {"name_ru": "Горох свежий", "name_en": "Green peas", "name_uk": "Горох свіжий", "name_kk": "Жасыл бұршақ", "calories": 81, "protein": 5.4, "fat": 0.4, "carbs": 14.5, "category": "vegetables"},
    {"name_ru": "Капуста белокочанная", "name_en": "Cabbage", "name_uk": "Капуста білокачанна", "name_kk": "Орамжапырақ", "calories": 27, "protein": 1.8, "fat": 0.1, "carbs": 6.8, "category": "vegetables"},
    {"name_ru": "Капуста цветная", "name_en": "Cauliflower", "name_uk": "Цвітна капуста", "name_kk": "Гүлді қырыққабат", "calories": 25, "protein": 1.9, "fat": 0.3, "carbs": 4.9, "category": "vegetables"},
    {"name_ru": "Картофель", "name_en": "Potato", "name_uk": "Картопля", "name_kk": "Картоп", "calories": 77, "protein": 2.0, "fat": 0.1, "carbs": 17.5, "category": "vegetables"},
    {"name_ru": "Кукуруза", "name_en": "Corn", "name_uk": "Кукурудза", "name_kk": "Жүгері", "calories": 86, "protein": 3.3, "fat": 1.4, "carbs": 18.7, "category": "vegetables"},
    {"name_ru": "Лук репчатый", "name_en": "Onion", "name_uk": "Цибуля ріпчаста", "name_kk": "Пияз", "calories": 41, "protein": 1.1, "fat": 0.1, "carbs": 10.4, "category": "vegetables"},
    {"name_ru": "Морковь", "name_en": "Carrot", "name_uk": "Морква", "name_kk": "Сәбіз", "calories": 41, "protein": 0.9, "fat": 0.2, "carbs": 9.6, "category": "vegetables"},
    {"name_ru": "Огурец", "name_en": "Cucumber", "name_uk": "Огірок", "name_kk": "Қияр", "calories": 15, "protein": 0.7, "fat": 0.1, "carbs": 2.8, "category": "vegetables"},
    {"name_ru": "Перец болгарский", "name_en": "Bell pepper", "name_uk": "Болгарський перець", "name_kk": "Болгар бұрышы", "calories": 31, "protein": 1.0, "fat": 0.3, "carbs": 6.0, "category": "vegetables"},
    {"name_ru": "Помидор", "name_en": "Tomato", "name_uk": "Помідор", "name_kk": "Қызанақ", "calories": 18, "protein": 0.9, "fat": 0.2, "carbs": 3.8, "category": "vegetables"},
    {"name_ru": "Свёкла", "name_en": "Beet", "name_uk": "Буряк", "name_kk": "Қызылша", "calories": 43, "protein": 1.6, "fat": 0.1, "carbs": 10.8, "category": "vegetables"},
    {"name_ru": "Сельдерей", "name_en": "Celery", "name_uk": "Селера", "name_kk": "Балдырған", "calories": 14, "protein": 0.7, "fat": 0.1, "carbs": 2.1, "category": "vegetables"},
    {"name_ru": "Шпинат", "name_en": "Spinach", "name_uk": "Шпинат", "name_kk": "Шпинат", "calories": 23, "protein": 2.9, "fat": 0.4, "carbs": 3.6, "category": "vegetables"},
    {"name_ru": "Чеснок", "name_en": "Garlic", "name_uk": "Часник", "name_kk": "Сарымсақ", "calories": 149, "protein": 6.4, "fat": 0.5, "carbs": 33.1, "category": "vegetables"},
    {"name_ru": "Тыква", "name_en": "Pumpkin", "name_uk": "Гарбуз", "name_kk": "Асқабақ", "calories": 26, "protein": 1.0, "fat": 0.1, "carbs": 6.5, "category": "vegetables"},
    {"name_ru": "Кабачок", "name_en": "Zucchini", "name_uk": "Кабачок", "name_kk": "Кабачок", "calories": 17, "protein": 1.2, "fat": 0.3, "carbs": 3.1, "category": "vegetables"},
    {"name_ru": "Салат листовой", "name_en": "Lettuce", "name_uk": "Салат листовий", "name_kk": "Жапырақты салат", "calories": 15, "protein": 1.4, "fat": 0.2, "carbs": 2.9, "category": "vegetables"},
    {"name_ru": "Редис", "name_en": "Radish", "name_uk": "Редиска", "name_kk": "Шалқан", "calories": 16, "protein": 0.7, "fat": 0.1, "carbs": 3.4, "category": "vegetables"},

    # === МЯСО ===
    {"name_ru": "Говядина", "name_en": "Beef", "name_uk": "Яловичина", "name_kk": "Сиыр еті", "calories": 187, "protein": 18.9, "fat": 12.4, "carbs": 0, "category": "meat"},
    {"name_ru": "Говяжий фарш", "name_en": "Ground beef", "name_uk": "Яловичий фарш", "name_kk": "Сиыр ету ұны", "calories": 214, "protein": 17.0, "fat": 17.0, "carbs": 0, "category": "meat"},
    {"name_ru": "Курица", "name_en": "Chicken", "name_uk": "Курка", "name_kk": "Тауық", "calories": 165, "protein": 20.1, "fat": 9.2, "carbs": 0, "category": "meat"},
    {"name_ru": "Куриная грудка", "name_en": "Chicken breast", "name_uk": "Куриная грудь", "name_kk": "Тауық өкпесі", "calories": 165, "protein": 31.0, "fat": 3.6, "carbs": 0, "category": "meat"},
    {"name_ru": "Куриное бедро", "name_en": "Chicken thigh", "name_uk": "Куриное стегно", "name_kk": "Тауық лапасы", "calories": 209, "protein": 18.0, "fat": 15.0, "carbs": 0, "category": "meat"},
    {"name_ru": "Куриный фарш", "name_en": "Ground chicken", "name_uk": "Куриний фарш", "name_kk": "Тауық ету ұны", "calories": 143, "protein": 20.0, "fat": 7.0, "carbs": 0, "category": "meat"},
    {"name_ru": "Свинина", "name_en": "Pork", "name_uk": "Свинина", "name_kk": "Шошқа еті", "calories": 242, "protein": 16.4, "fat": 21.7, "carbs": 0, "category": "meat"},
    {"name_ru": "Индейка", "name_en": "Turkey", "name_uk": "Індичка", "name_kk": "Индек еті", "calories": 189, "protein": 20.3, "fat": 11.4, "carbs": 0, "category": "meat"},
    {"name_ru": "Баранина", "name_en": "Lamb", "name_uk": "Баранина", "name_kk": "Қой еті", "calories": 209, "protein": 17.0, "fat": 16.7, "carbs": 0, "category": "meat"},
    {"name_ru": "Вареная колбаса", "name_en": "Boiled sausage", "name_uk": "Вареная колбаса", "name_kk": "Қайнатылған құйма", "calories": 260, "protein": 12.0, "fat": 22.0, "carbs": 2.0, "category": "meat"},

    # === МОЛОЧНОЕ ===
    {"name_ru": "Йогурт натуральный", "name_en": "Natural yogurt", "name_uk": "Йогурт натуральний", "name_kk": "Табиғи йогурт", "calories": 63, "protein": 3.5, "fat": 0.4, "carbs": 3.5, "category": "dairy"},
    {"name_ru": "Йогурт 5% жирности", "name_en": "Yogurt 5%", "name_uk": "Йогурт 5%", "name_kk": "Йогурт 5%", "calories": 90, "protein": 3.5, "fat": 5.0, "carbs": 6.2, "category": "dairy"},
    {"name_ru": "Кефир", "name_en": "Kefir", "name_uk": "Кефір", "name_kk": "Кефир", "calories": 41, "protein": 3.4, "fat": 1.0, "carbs": 3.2, "category": "dairy"},
    {"name_ru": "Молоко коровье", "name_en": "Cow milk", "name_uk": "Коров'яче молоко", "name_kk": "Сиыр сүті", "calories": 64, "protein": 3.2, "fat": 3.6, "carbs": 4.8, "category": "dairy"},
    {"name_ru": "Молоко нежирное", "name_en": "Skim milk", "name_uk": "Знежирене молоко", "name_kk": "Ішектен жұқтарылған сүт", "calories": 35, "protein": 3.3, "fat": 0.1, "carbs": 4.8, "category": "dairy"},
    {"name_ru": "Сметана 20%", "name_en": "Sour cream 20%", "name_uk": "Сметана 20%", "name_kk": "Сметана 20%", "calories": 204, "protein": 2.8, "fat": 20.0, "carbs": 3.2, "category": "dairy"},
    {"name_ru": "Творог 0% (нежирный)", "name_en": "Cottage cheese 0%", "name_uk": "Творог 0%", "name_kk": "Творог 0%", "calories": 90, "protein": 18.0, "fat": 0.5, "carbs": 1.5, "category": "dairy"},
    {"name_ru": "Творог 5% (полусладкий)", "name_en": "Cottage cheese 5%", "name_uk": "Творог 5%", "name_kk": "Творог 5%", "calories": 121, "protein": 17.0, "fat": 5.0, "carbs": 1.8, "category": "dairy"},
    {"name_ru": "Сыр Российский", "name_en": "Russian cheese", "name_uk": "Сир Російський", "name_kk": "Ресей сыры", "calories": 360, "protein": 24.0, "fat": 29.0, "carbs": 0, "category": "dairy"},
    {"name_ru": "Сыр Голландский", "name_en": "Dutch cheese", "name_uk": "Сир Голландський", "name_kk": "Голландия сыры", "calories": 380, "protein": 27.0, "fat": 30.0, "carbs": 0, "category": "dairy"},
    {"name_ru": "Сыр Пармезан", "name_en": "Parmesan", "name_uk": "Сир Пармезан", "name_kk": "Пармезан сыры", "calories": 392, "protein": 37.0, "fat": 30.0, "carbs": 1.0, "category": "dairy"},
    {"name_ru": "Масло сливочное", "name_en": "Butter", "name_uk": "Вершкове масло", "name_kk": "Сүт майы", "calories": 717, "protein": 0.8, "fat": 80.0, "carbs": 0.1, "category": "dairy"},

    # === ЗЛАКИ ===
    {"name_ru": "Гречневая каша", "name_en": "Buckwheat", "name_uk": "Гречневої каші", "name_kk": "Гречка құймасы", "calories": 335, "protein": 12.6, "fat": 2.7, "carbs": 71.5, "category": "grains"},
    {"name_ru": "Овсяная каша", "name_en": "Oatmeal", "name_uk": "Вівсяної каші", "name_kk": "Сұлы құймасы", "calories": 389, "protein": 17.0, "fat": 6.9, "carbs": 66.3, "category": "grains"},
    {"name_ru": "Пшеничная каша", "name_en": "Wheat porridge", "name_uk": "Пшеничної каші", "name_kk": "Бидай құймасы", "calories": 340, "protein": 12.3, "fat": 1.7, "carbs": 71.2, "category": "grains"},
    {"name_ru": "Рис белый", "name_en": "White rice", "name_uk": "Білий рис", "name_kk": "Ақ күлпінар", "calories": 344, "protein": 7.0, "fat": 2.7, "carbs": 78.9, "category": "grains"},
    {"name_ru": "Рис коричневый", "name_en": "Brown rice", "name_uk": "Коричневий рис", "name_kk": "Құм түстес күлпінар", "calories": 365, "protein": 8.0, "fat": 3.0, "carbs": 77.0, "category": "grains"},
    {"name_ru": "Хлеб белый", "name_en": "White bread", "name_uk": "Білий хліб", "name_kk": "Ақ нан", "calories": 264, "protein": 8.4, "fat": 2.0, "carbs": 49.4, "category": "grains"},
    {"name_ru": "Хлеб чёрный", "name_en": "Black bread", "name_uk": "Чорний хліб", "name_kk": "Қара нан", "calories": 206, "protein": 6.6, "fat": 1.3, "carbs": 40.5, "category": "grains"},
    {"name_ru": "Хлеб отрубной", "name_en": "Bran bread", "name_uk": "Хліб з висівками", "name_kk": "Түйіндерді нан", "calories": 227, "protein": 7.5, "fat": 1.5, "carbs": 43.0, "category": "grains"},
    {"name_ru": "Макаронные изделия", "name_en": "Pasta", "name_uk": "Макаронні вироби", "name_kk": "Макарон өндірістері", "calories": 344, "protein": 13.0, "fat": 1.8, "carbs": 71.0, "category": "grains"},
    {"name_ru": "Манная крупа", "name_en": "Semolina", "name_uk": "Манна крупа", "name_kk": "Манная крупа", "calories": 333, "protein": 10.3, "fat": 1.0, "carbs": 72.0, "category": "grains"},

    # === ОРЕХИ И СЕМЕНА ===
    {"name_ru": "Миндаль", "name_en": "Almonds", "name_uk": "Мигдаль", "name_kk": "Миндаль", "calories": 579, "protein": 21.2, "fat": 49.9, "carbs": 21.5, "category": "nuts"},
    {"name_ru": "Грецкий орех", "name_en": "Walnut", "name_uk": "Грецький горіх", "name_kk": "Жүндеу", "calories": 654, "protein": 15.2, "fat": 65.2, "carbs": 13.7, "category": "nuts"},
    {"name_ru": "Кешью", "name_en": "Cashew", "name_uk": "Кешью", "name_kk": "Кешью", "calories": 553, "protein": 18.2, "fat": 43.9, "carbs": 30.2, "category": "nuts"},
    {"name_ru": "Арахис", "name_en": "Peanuts", "name_uk": "Арахіс", "name_kk": "Арахис", "calories": 567, "protein": 26.3, "fat": 49.2, "carbs": 16.1, "category": "nuts"},
    {"name_ru": "Кедровые орехи", "name_en": "Pine nuts", "name_uk": "Кедрові горіхи", "name_kk": "Қарағай ореки", "calories": 620, "protein": 13.7, "fat": 60.0, "carbs": 13.1, "category": "nuts"},
    {"name_ru": "Фундук", "name_en": "Hazelnuts", "name_uk": "Лісний горіх", "name_kk": "Фундук", "calories": 628, "protein": 16.1, "fat": 61.5, "carbs": 16.7, "category": "nuts"},
    {"name_ru": "Семена подсолнечника", "name_en": "Sunflower seeds", "name_uk": "Насіння соняшника", "name_kk": "Күн ағысының тұқымы", "calories": 584, "protein": 20.7, "fat": 52.9, "carbs": 20.0, "category": "nuts"},
    {"name_ru": "Семена тыквы", "name_en": "Pumpkin seeds", "name_uk": "Насіння гарбуза", "name_kk": "Асқабақ тұқымы", "calories": 559, "protein": 24.5, "fat": 49.0, "carbs": 10.7, "category": "nuts"},
    {"name_ru": "Кунжут", "name_en": "Sesame", "name_uk": "Сезам", "name_kk": "Кунжут", "calories": 563, "protein": 17.7, "fat": 48.7, "carbs": 23.4, "category": "nuts"},
    {"name_ru": "Масло ореховое", "name_en": "Nut butter", "name_uk": "Ореховое масло", "name_kk": "Орек майы", "calories": 588, "protein": 24.0, "fat": 50.0, "carbs": 20.0, "category": "nuts"},

    # === РЫБА ===
    {"name_ru": "Горбуша", "name_en": "Pink salmon", "name_uk": "Горбуша", "name_kk": "Қызыл балық", "calories": 142, "protein": 21.0, "fat": 6.5, "carbs": 0, "category": "fish"},
    {"name_ru": "Креветки", "name_en": "Shrimp", "name_uk": "Креветки", "name_kk": "Асшаян", "calories": 99, "protein": 18.9, "fat": 2.2, "carbs": 0, "category": "fish"},
    {"name_ru": "Лосось", "name_en": "Salmon", "name_uk": "Лосось", "name_kk": "Лосось", "calories": 208, "protein": 20.0, "fat": 13.0, "carbs": 0, "category": "fish"},
    {"name_ru": "Минтай", "name_en": "Pollock", "name_uk": "Мінтай", "name_kk": "Минтай", "calories": 72, "protein": 15.9, "fat": 0.7, "carbs": 0, "category": "fish"},
    {"name_ru": "Сёмга", "name_en": "Trout", "name_uk": "Сьомга", "name_kk": "Форель", "calories": 219, "protein": 20.8, "fat": 15.1, "carbs": 0, "category": "fish"},
    {"name_ru": "Скумбрия", "name_en": "Mackerel", "name_uk": "Скумбрія", "name_kk": "Скумбрия", "calories": 262, "protein": 18.0, "fat": 13.2, "carbs": 0, "category": "fish"},
    {"name_ru": "Сельдь", "name_en": "Herring", "name_uk": "Оселедець", "name_kk": "Майшабақ", "calories": 217, "protein": 17.7, "fat": 19.5, "carbs": 0, "category": "fish"},
    {"name_ru": "Тунец", "name_en": "Tuna", "name_uk": "Тунець", "name_kk": "Тунец", "calories": 136, "protein": 23.3, "fat": 4.9, "carbs": 0, "category": "fish"},
    {"name_ru": "Треска", "name_en": "Cod", "name_uk": "Тріска", "name_kk": "Треска", "calories": 69, "protein": 16.0, "fat": 0.4, "carbs": 0, "category": "fish"},
    {"name_ru": "Хек", "name_en": "Hake", "name_uk": "Хек", "name_kk": "Хек", "calories": 86, "protein": 16.6, "fat": 2.2, "carbs": 0, "category": "fish"},
    {"name_ru": "Кальмар", "name_en": "Squid", "name_uk": "Кальмар", "name_kk": "Есік балығы", "calories": 86, "protein": 19.2, "fat": 0.3, "carbs": 0, "category": "fish"},
    {"name_ru": "Мидии", "name_en": "Mussels", "name_uk": "Мідії", "name_kk": "Мүйіс", "calories": 77, "protein": 11.5, "fat": 2.0, "carbs": 0, "category": "fish"},

    # === СЛАДКОЕ ===
    {"name_ru": "Варенье", "name_en": "Jam", "name_uk": "Варення", "name_kk": "Тосап", "calories": 238, "protein": 0.3, "fat": 0.1, "carbs": 65.0, "category": "sweets"},
    {"name_ru": "Зефир", "name_en": "Marshmallow", "name_uk": "Зефір", "name_kk": "Зефир", "calories": 304, "protein": 0.8, "fat": 0, "carbs": 78.3, "category": "sweets"},
    {"name_ru": "Мёд", "name_en": "Honey", "name_uk": "Мед", "name_kk": "Бал", "calories": 304, "protein": 0.8, "fat": 0, "carbs": 82.4, "category": "sweets"},
    {"name_ru": "Мороженое пломбир", "name_en": "Ice cream", "name_uk": "Морозиво пломбір", "name_kk": "Балмұздақ", "calories": 227, "protein": 3.7, "fat": 12.0, "carbs": 27.7, "category": "sweets"},
    {"name_ru": "Печенье", "name_en": "Cookies", "name_uk": "Печиво", "name_kk": "Печенье", "calories": 424, "protein": 7.5, "fat": 14.8, "carbs": 67.1, "category": "sweets"},
    {"name_ru": "Пирог яблочный", "name_en": "Apple pie", "name_uk": "Яблучний пиріг", "name_kk": "Алмалы пирог", "calories": 265, "protein": 4.0, "fat": 11.0, "carbs": 38.0, "category": "sweets"},
    {"name_ru": "Сахар", "name_en": "Sugar", "name_uk": "Цукор", "name_kk": "Қант", "calories": 387, "protein": 0, "fat": 0, "carbs": 99.9, "category": "sweets"},
    {"name_ru": "Торт бисквитный", "name_en": "Sponge cake", "name_uk": "Бісквітний торт", "name_kk": "Бисквит торты", "calories": 350, "protein": 5.0, "fat": 12.0, "carbs": 58.0, "category": "sweets"},
    {"name_ru": "Шоколад горький", "name_en": "Dark chocolate", "name_uk": "Гіркий шоколад", "name_kk": "Ащы шоколад", "calories": 539, "protein": 5.4, "fat": 35.4, "carbs": 56.9, "category": "sweets"},
    {"name_ru": "Шоколад молочный", "name_en": "Milk chocolate", "name_uk": "Молочний шоколад", "name_kk": "Сүтті шоколад", "calories": 535, "protein": 6.9, "fat": 29.6, "carbs": 59.4, "category": "sweets"},

    # === НАПИТКИ ===
    {"name_ru": "Апельсиновый сок", "name_en": "Orange juice", "name_uk": "Апельсиновий сік", "name_kk": "Апельсин шырыны", "calories": 45, "protein": 0.7, "fat": 0.2, "carbs": 10.4, "category": "drinks"},
    {"name_ru": "Вода", "name_en": "Water", "name_uk": "Вода", "name_kk": "Су", "calories": 0, "protein": 0, "fat": 0, "carbs": 0, "category": "drinks"},
    {"name_ru": "Зелёный чай", "name_en": "Green tea", "name_uk": "Зелений чай", "name_kk": "Жасыл шай", "calories": 1, "protein": 0, "fat": 0, "carbs": 0, "category": "drinks"},
    {"name_ru": "Кефир 1%", "name_en": "Kefir 1%", "name_uk": "Кефір 1%", "name_kk": "Кефир 1%", "calories": 40, "protein": 3.0, "fat": 1.0, "carbs": 4.0, "category": "drinks"},
    {"name_ru": "Кола", "name_en": "Cola", "name_uk": "Кола", "name_kk": "Кола", "calories": 42, "protein": 0, "fat": 0, "carbs": 10.6, "category": "drinks"},
    {"name_ru": "Кофе чёрный", "name_en": "Black coffee", "name_uk": "Чорна кава", "name_kk": "Қара кофе", "calories": 2, "protein": 0.3, "fat": 0, "carbs": 0, "category": "drinks"},
    {"name_ru": "Молоко 2,5% (напиток)", "name_en": "Milk 2.5% (drink)", "name_uk": "Молоко 2,5% (напій)", "name_kk": "Сүт 2,5% (сусын)", "calories": 52, "protein": 2.8, "fat": 2.5, "carbs": 4.7, "category": "drinks"},
    {"name_ru": "Смузи зелёный", "name_en": "Green smoothie", "name_uk": "Зелений смузі", "name_kk": "Жасыл смузи", "calories": 60, "protein": 1.5, "fat": 0.5, "carbs": 14.0, "category": "drinks"},
    {"name_ru": "Томатный сок", "name_en": "Tomato juice", "name_uk": "Томатний сік", "name_kk": "Қызанақ шырыны", "calories": 18, "protein": 0.9, "fat": 0, "carbs": 3.5, "category": "drinks"},
    {"name_ru": "Чёрный чай", "name_en": "Black tea", "name_uk": "Чорний чай", "name_kk": "Қара шай", "calories": 1, "protein": 0.1, "fat": 0, "carbs": 0.3, "category": "drinks"},

    # === ВИТАМИНЫ И ДОБАВКИ ===
    {"name_ru": "Витамин C (таблетка)", "name_en": "Vitamin C (tablet)", "name_uk": "Вітамін C (таблетка)", "name_kk": "C Витамины (таблетка)", "calories": 4, "protein": 0, "fat": 0, "carbs": 1.0, "category": "supplements"},
    {"name_ru": "Витамин D3 (капсула)", "name_en": "Vitamin D3 (capsule)", "name_uk": "Вітамін D3 (капсула)", "name_kk": "D3 Витамины (капсула)", "calories": 3, "protein": 0, "fat": 0.2, "carbs": 0.2, "category": "supplements"},
    {"name_ru": "Витамин B12 (таблетка)", "name_en": "Vitamin B12 (tablet)", "name_uk": "Вітамін B12 (таблетка)", "name_kk": "B12 Витамины (таблетка)", "calories": 0, "protein": 0, "fat": 0, "carbs": 0, "category": "supplements"},
    {"name_ru": "Омега-3 (капсула)", "name_en": "Omega-3 (capsule)", "name_uk": "Омега-3 (капсула)", "name_kk": "Омега-3 (капсула)", "calories": 9, "protein": 0, "fat": 1.0, "carbs": 0, "category": "supplements"},
    {"name_ru": "Мультивитамины", "name_en": "Multivitamins", "name_uk": "Мультивітаміни", "name_kk": "Көпвітамины", "calories": 5, "protein": 0.2, "fat": 0.1, "carbs": 0.8, "category": "supplements"},
    {"name_ru": "Магний (таблетка)", "name_en": "Magnesium (tablet)", "name_uk": "Магній (таблетка)", "name_kk": "Магний (таблетка)", "calories": 2, "protein": 0, "fat": 0, "carbs": 0.5, "category": "supplements"},
    {"name_ru": "Кальций (таблетка)", "name_en": "Calcium (tablet)", "name_uk": "Кальцій (таблетка)", "name_kk": "Кальций (таблетка)", "calories": 3, "protein": 0, "fat": 0, "carbs": 0.3, "category": "supplements"},
    {"name_ru": "Железо (таблетка)", "name_en": "Iron (tablet)", "name_uk": "Залізо (таблетка)", "name_kk": "Темір (таблетка)", "calories": 1, "protein": 0, "fat": 0, "carbs": 0.2, "category": "supplements"},
    {"name_ru": "Цинк (таблетка)", "name_en": "Zinc (tablet)", "name_uk": "Цинк (таблетка)", "name_kk": "Цинк (таблетка)", "calories": 1, "protein": 0, "fat": 0, "carbs": 0.1, "category": "supplements"},
    {"name_ru": "Пробиотики (капсула)", "name_en": "Probiotics (capsule)", "name_uk": "Пробіотики (капсула)", "name_kk": "Пробиотиктер (капсула)", "calories": 5, "protein": 0.5, "fat": 0, "carbs": 0.5, "category": "supplements"},

    # === СПОРТИВНОЕ ПИТАНИЕ ===
    {"name_ru": "Протеиновый коктейль (порция)", "name_en": "Protein shake (serving)", "name_uk": "Протеїновий коктейль (порція)", "name_kk": "Ақуыл коктейл (порция)", "calories": 120, "protein": 25.0, "fat": 1.5, "carbs": 5.0, "category": "sports_nutrition"},
    {"name_ru": "Изолят белка (сывороточный)", "name_en": "Whey protein isolate", "name_uk": "Ізолят білку (сироваткові)", "name_kk": "Ақуыл изоляты (құс ынауы)", "calories": 110, "protein": 25.0, "fat": 0.5, "carbs": 2.0, "category": "sports_nutrition"},
    {"name_ru": "Казеиновый протеин", "name_en": "Casein protein", "name_uk": "Казеїновий протеїн", "name_kk": "Казеин ақуылы", "calories": 115, "protein": 26.0, "fat": 1.0, "carbs": 1.5, "category": "sports_nutrition"},
    {"name_ru": "BCAA (аминокислоты)", "name_en": "BCAA amino acids", "name_uk": "BCAA (амінокислоти)", "name_kk": "BCAA (аминокислоталар)", "calories": 15, "protein": 3.5, "fat": 0, "carbs": 1.0, "category": "sports_nutrition"},
    {"name_ru": "Креатин моногидрат", "name_en": "Creatine monohydrate", "name_uk": "Креатин моногідрат", "name_kk": "Креатин моногидрат", "calories": 0, "protein": 0, "fat": 0, "carbs": 0, "category": "sports_nutrition"},
    {"name_ru": "L-карнитин (жидкость)", "name_en": "L-carnitine (liquid)", "name_uk": "L-карнітин (рідина)", "name_kk": "L-карнитин (сұйықтық)", "calories": 5, "protein": 0, "fat": 0, "carbs": 1.0, "category": "sports_nutrition"},
    {"name_ru": "Гейнер (порция)", "name_en": "Weight gainer (serving)", "name_uk": "Гейнер (порція)", "name_kk": "Салмақты ойындауш (порция)", "calories": 350, "protein": 20.0, "fat": 6.0, "carbs": 50.0, "category": "sports_nutrition"},
    {"name_ru": "Батончик протеиновый", "name_en": "Protein bar", "name_uk": "Протеїновий батончик", "name_kk": "Ақуыл таңғасы", "calories": 230, "protein": 20.0, "fat": 7.0, "carbs": 18.0, "category": "sports_nutrition"},
    {"name_ru": "Закуска протеиновая", "name_en": "Protein chips", "name_uk": "Протеїнові чипси", "name_kk": "Ақуыл чипстері", "calories": 150, "protein": 18.0, "fat": 4.0, "carbs": 8.0, "category": "sports_nutrition"},
    {"name_ru": "Энергетический гель", "name_en": "Energy gel", "name_uk": "Енергетичний гель", "name_kk": "Энергетикалық гель", "calories": 100, "protein": 0, "fat": 0, "carbs": 25.0, "category": "sports_nutrition"},
    {"name_ru": "Углеводный напиток", "name_en": "Carbohydrate drink", "name_uk": "Вуглеводний напій", "name_kk": "Көмірөндіктілік сусын", "calories": 80, "protein": 0, "fat": 0, "carbs": 20.0, "category": "sports_nutrition"},
    {"name_ru": "Коллагеновый пептид", "name_en": "Collagen peptide", "name_uk": "Колаген пептид", "name_kk": "Коллаген пептид", "calories": 100, "protein": 25.0, "fat": 0, "carbs": 0, "category": "sports_nutrition"},

    # === ДРУГОЕ ===
    {"name_ru": "Бобы чёрные", "name_en": "Black beans", "name_uk": "Чорні боби", "name_kk": "Қара бұршақ", "calories": 341, "protein": 21.6, "fat": 1.4, "carbs": 62.4, "category": "other"},
    {"name_ru": "Горчица", "name_en": "Mustard", "name_uk": "Гірчиця", "name_kk": "Қышқыл", "calories": 67, "protein": 4.0, "fat": 4.0, "carbs": 5.0, "category": "other"},
    {"name_ru": "Майонез", "name_en": "Mayonnaise", "name_uk": "Майонез", "name_kk": "Майонез", "calories": 680, "protein": 2.8, "fat": 74.0, "carbs": 2.6, "category": "other"},
    {"name_ru": "Маслины", "name_en": "Olives", "name_uk": "Маслини", "name_kk": "Зәйтүн", "calories": 145, "protein": 1.0, "fat": 15.3, "carbs": 3.8, "category": "other"},
    {"name_ru": "Нут", "name_en": "Chickpeas", "name_uk": "Нут", "name_kk": "Бұршақ", "calories": 364, "protein": 19.0, "fat": 6.0, "carbs": 61.0, "category": "other"},
    {"name_ru": "Оливковое масло", "name_en": "Olive oil", "name_uk": "Оливкова олія", "name_kk": "Зәйтүн майы", "calories": 884, "protein": 0, "fat": 100.0, "carbs": 0, "category": "other"},
    {"name_ru": "Яйцо куриное", "name_en": "Chicken egg", "name_uk": "Куряче яйце", "name_kk": "Тауық жұмыртқасы", "calories": 155, "protein": 13.0, "fat": 11.0, "carbs": 1.1, "category": "other"},
    {"name_ru": "Чечевица", "name_en": "Lentils", "name_uk": "Сочевиця", "name_kk": "Жасымық", "calories": 353, "protein": 24.0, "fat": 1.5, "carbs": 60.0, "category": "other"},
    {"name_ru": "Соевый соус", "name_en": "Soy sauce", "name_uk": "Соєвий соус", "name_kk": "Соя соусы", "calories": 53, "protein": 5.6, "fat": 0, "carbs": 4.9, "category": "other"},
    {"name_ru": "Тофу", "name_en": "Tofu", "name_uk": "Тофу", "name_kk": "Тофу", "calories": 76, "protein": 8.0, "fat": 4.8, "carbs": 1.9, "category": "other"},
    {"name_ru": "Борщ", "name_en": "Borscht", "name_uk": "Борщ", "name_kk": "Борщ", "calories": 55, "protein": 2.8, "fat": 2.1, "carbs": 7.2, "category": "other"},
    {"name_ru": "Пельмени", "name_en": "Dumplings", "name_uk": "Пельмені", "name_kk": "Пельмендер", "calories": 275, "protein": 11.0, "fat": 12.0, "carbs": 29.0, "category": "other"},
    {"name_ru": "Вареники с картошкой", "name_en": "Potato dumplings", "name_uk": "Вареники з картоплею", "name_kk": "Картопты вареник", "calories": 190, "protein": 5.0, "fat": 3.5, "carbs": 35.0, "category": "other"},
    {"name_ru": "Вареники с творогом", "name_en": "Cottage cheese dumplings", "name_uk": "Вареники з сиром", "name_kk": "Сүзбелі вареник", "calories": 210, "protein": 9.0, "fat": 5.0, "carbs": 33.0, "category": "other"},
]
