# База продуктов питания (калории на 100г)
# Формат: name_ru, name_en, name_uk, name_kk, calories, protein, fat, carbs, category

FOODS = [
    # === ФРУКТЫ ===
    {"name_ru": "Абрикос", "name_en": "Apricot", "name_uk": "Абрикос", "name_kk": "Өрік", "calories": 44, "protein": 0.9, "fat": 0.1, "carbs": 9.0, "category": "fruits"},
    {"name_ru": "Авокадо", "name_en": "Avocado", "name_uk": "Авокадо", "name_kk": "Авокадо", "calories": 160, "protein": 2.0, "fat": 15.0, "carbs": 9.0, "category": "fruits"},
    {"name_ru": "Ананас", "name_en": "Pineapple", "name_uk": "Ананас", "name_kk": "Ананас", "calories": 50, "protein": 0.5, "fat": 0.1, "carbs": 13.0, "category": "fruits"},
    {"name_ru": "Апельсин", "name_en": "Orange", "name_uk": "Апельсин", "name_kk": "Апельсин", "calories": 43, "protein": 0.9, "fat": 0.2, "carbs": 8.1, "category": "fruits"},
    {"name_ru": "Арбуз", "name_en": "Watermelon", "name_uk": "Кавун", "name_kk": "Қарбыз", "calories": 30, "protein": 0.6, "fat": 0.1, "carbs": 7.5, "category": "fruits"},
    {"name_ru": "Банан", "name_en": "Banana", "name_uk": "Банан", "name_kk": "Банан", "calories": 89, "protein": 1.1, "fat": 0.3, "carbs": 22.8, "category": "fruits"},
    {"name_ru": "Виноград", "name_en": "Grapes", "name_uk": "Виноград", "name_kk": "Жүзім", "calories": 67, "protein": 0.6, "fat": 0.2, "carbs": 17.2, "category": "fruits"},
    {"name_ru": "Вишня", "name_en": "Cherry", "name_uk": "Вишня", "name_kk": "Шие", "calories": 52, "protein": 0.8, "fat": 0.5, "carbs": 10.6, "category": "fruits"},
    {"name_ru": "Груша", "name_en": "Pear", "name_uk": "Груша", "name_kk": "Алмұрт", "calories": 57, "protein": 0.4, "fat": 0.3, "carbs": 15.2, "category": "fruits"},
    {"name_ru": "Дыня", "name_en": "Melon", "name_uk": "Диня", "name_kk": "Қауын", "calories": 34, "protein": 0.6, "fat": 0.3, "carbs": 7.4, "category": "fruits"},
    {"name_ru": "Киви", "name_en": "Kiwi", "name_uk": "Ківі", "name_kk": "Киви", "calories": 61, "protein": 1.1, "fat": 0.5, "carbs": 14.7, "category": "fruits"},
    {"name_ru": "Клубника", "name_en": "Strawberry", "name_uk": "Полуниця", "name_kk": "Құлпынай", "calories": 30, "protein": 0.8, "fat": 0.4, "carbs": 5.5, "category": "fruits"},
    {"name_ru": "Лимон", "name_en": "Lemon", "name_uk": "Лимон", "name_kk": "Лимон", "calories": 29, "protein": 1.1, "fat": 0.3, "carbs": 3.0, "category": "fruits"},
    {"name_ru": "Малина", "name_en": "Raspberry", "name_uk": "Малина", "name_kk": "Таңқурай", "calories": 46, "protein": 0.8, "fat": 0.5, "carbs": 8.3, "category": "fruits"},
    {"name_ru": "Манго", "name_en": "Mango", "name_uk": "Манго", "name_kk": "Манго", "calories": 60, "protein": 0.8, "fat": 0.4, "carbs": 14.8, "category": "fruits"},
    {"name_ru": "Мандарин", "name_en": "Tangerine", "name_uk": "Мандарин", "name_kk": "Мандарин", "calories": 38, "protein": 0.8, "fat": 0.2, "carbs": 7.5, "category": "fruits"},
    {"name_ru": "Персик", "name_en": "Peach", "name_uk": "Персик", "name_kk": "Шабдалы", "calories": 39, "protein": 0.9, "fat": 0.1, "carbs": 9.5, "category": "fruits"},
    {"name_ru": "Слива", "name_en": "Plum", "name_uk": "Слива", "name_kk": "Өрік", "calories": 46, "protein": 0.7, "fat": 0.3, "carbs": 9.6, "category": "fruits"},
    {"name_ru": "Черника", "name_en": "Blueberry", "name_uk": "Чорниця", "name_kk": "Көкжидек", "calories": 57, "protein": 0.7, "fat": 0.3, "carbs": 14.5, "category": "fruits"},
    {"name_ru": "Яблоко", "name_en": "Apple", "name_uk": "Яблуко", "name_kk": "Алма", "calories": 52, "protein": 0.3, "fat": 0.2, "carbs": 14.0, "category": "fruits"},
    {"name_ru": "Гранат", "name_en": "Pomegranate", "name_uk": "Гранат", "name_kk": "Анар", "calories": 83, "protein": 1.7, "fat": 1.2, "carbs": 18.7, "category": "fruits"},
    {"name_ru": "Папайя", "name_en": "Papaya", "name_uk": "Папайя", "name_kk": "Папайя", "calories": 39, "protein": 0.6, "fat": 0.1, "carbs": 9.8, "category": "fruits"},

    # === ОВОЩИ ===
    {"name_ru": "Баклажан", "name_en": "Eggplant", "name_uk": "Баклажан", "name_kk": "Баклажан", "calories": 24, "protein": 1.2, "fat": 0.1, "carbs": 5.5, "category": "vegetables"},
    {"name_ru": "Брокколи", "name_en": "Broccoli", "name_uk": "Броколі", "name_kk": "Брокколи", "calories": 34, "protein": 2.8, "fat": 0.4, "carbs": 7.0, "category": "vegetables"},
    {"name_ru": "Горох свежий", "name_en": "Green peas", "name_uk": "Горох свіжий", "name_kk": "Жасыл бұршақ", "calories": 81, "protein": 5.4, "fat": 0.4, "carbs": 14.5, "category": "vegetables"},
    {"name_ru": "Капуста белокочанная", "name_en": "Cabbage", "name_uk": "Капуста білокачанна", "name_kk": "Орамжапырақ", "calories": 27, "protein": 1.8, "fat": 0.1, "carbs": 6.8, "category": "vegetables"},
    {"name_ru": "Капуста цветная", "name_en": "Cauliflower", "name_uk": "Цвітна капуста", "name_kk": "Гүлді қырыққабат", "calories": 25, "protein": 1.9, "fat": 0.3, "carbs": 4.9, "category": "vegetables"},
    {"name_ru": "Картофель", "name_en": "Potato", "name_uk": "Картопля", "name_kk": "Картоп", "calories": 77, "protein": 2.0, "fat": 0.1, "carbs": 17.5, "category": "vegetables"},
    {"name_ru": "Кукуруза", "name_en": "Corn", "name_uk": "Кукурудза", "name_kk": "Жүгері", "calories": 86, "protein": 3.3, "fat": 1.4, "carbs": 18.7, "category": "vegetables"},
    {"name_ru": "Лук репчатый", "name_en": "Onion", "name_uk": "Цибуля ріпчаста", "name_kk": "Пияз", "calories": 41, "protein": 1.1, "fat": 0.1, "carbs": 10.4, "category": "vegetables"},
    {"name_ru": "Морковь", "name_en": "Carrot", "name_uk": "Морква", "name_kk": "Сәбіз", "calories": 41, "protein": 0.9, "fat": 0.2, "carbs": 9.6, "category": "vegetables"},
    {"name_ru": "Огурец", "name_en": "Cucumber", "name_uk": "Огірок", "name_kk": "Қияр", "calories": 15, "protein": 0.7, "fat": 0.1, "carbs": 2.8, "category": "vegetables"},
    {"name_ru": "Перец болгарский", "name_en": "Bell pepper", "name_uk": "Болгарський перець", "name_kk": "Болгар бұрышы", "calories": 31, "protein": 1.0, "fat": 0.3, "carbs": 6.0, "category": "vegetables"},
    {"name_ru": "Помидор", "name_en": "Tomato", "name_uk": "Помідор", "name_kk": "Қызанақ", "calories": 18, "protein": 0.9, "fat": 0.2, "carbs": 3.8, "category": "vegetables"},
    {"name_ru": "Свёкла", "name_en": "Beet", "name_uk": "Буряк", "name_kk": "Қызылша", "calories": 43, "protein": 1.6, "fat": 0.1, "carbs": 10.8, "category": "vegetables"},
    {"name_ru": "Сельдерей", "name_en": "Celery", "name_uk": "Селера", "name_kk": "Балдырған", "calories": 14, "protein": 0.7, "fat": 0.1, "carbs": 2.1, "category": "vegetables"},
    {"name_ru": "Шпинат", "name_en": "Spinach", "name_uk": "Шпинат", "name_kk": "Шпинат", "calories": 23, "protein": 2.9, "fat": 0.4, "carbs": 3.6, "category": "vegetables"},
    {"name_ru": "Чеснок", "name_en": "Garlic", "name_uk": "Часник", "name_kk": "Сарымсақ", "calories": 149, "protein": 6.4, "fat": 0.5, "carbs": 33.1, "category": "vegetables"},
    {"name_ru": "Тыква", "name_en": "Pumpkin", "name_uk": "Гарбуз", "name_kk": "Асқабақ", "calories": 26, "protein": 1.0, "fat": 0.1, "carbs": 6.5, "category": "vegetables"},
    {"name_ru": "Кабачок", "name_en": "Zucchini", "name_uk": "Кабачок", "name_kk": "Кабачок", "calories": 17, "protein": 1.2, "fat": 0.3, "carbs": 3.1, "category": "vegetables"},
    {"name_ru": "Салат листовой", "name_en": "Lettuce", "name_uk": "Салат листовий", "name_kk": "Жапырақты салат", "calories": 15, "protein": 1.4, "fat": 0.2, "carbs": 2.9, "category": "vegetables"},
    {"name_ru": "Редис", "name_en": "Radish", "name_uk": "Редиска", "name_kk": "Шалқан", "calories": 16, "protein": 0.7, "fat": 0.1, "carbs": 3.4, "category": "vegetables"},

    # === МЯСО ===
    {"name_ru": "Говядина", "name_en": "Beef", "name_uk": "Яловичина", "name_kk": "Сиыр еті", "calories": 187, "protein": 18.9, "fat": 12.4, "carbs": 0, "category": "meat"},
    {"name_ru": "Грудка куриная", "name_en": "Chicken breast", "name_uk": "Куряча грудка", "name_kk": "Тауық еті", "calories": 165, "protein": 31.0, "fat": 3.6, "carbs": 0, "category": "meat"},
    {"name_ru": "Индейка", "name_en": "Turkey", "name_uk": "Індичка", "name_kk": "Күрке мауқы еті", "calories": 189, "protein": 28.0, "fat": 7.7, "carbs": 0, "category": "meat"},
    {"name_ru": "Курица (бедро)", "name_en": "Chicken thigh", "name_uk": "Куряче стегно", "name_kk": "Тауық санының еті", "calories": 209, "protein": 24.8, "fat": 11.5, "carbs": 0, "category": "meat"},
    {"name_ru": "Свинина", "name_en": "Pork", "name_uk": "Свинина", "name_kk": "Шошқа еті", "calories": 242, "protein": 16.0, "fat": 21.0, "carbs": 0, "category": "meat"},
    {"name_ru": "Телятина", "name_en": "Veal", "name_uk": "Телятина", "name_kk": "Бұзау еті", "calories": 131, "protein": 19.7, "fat": 5.6, "carbs": 0, "category": "meat"},
    {"name_ru": "Утка", "name_en": "Duck", "name_uk": "Качка", "name_kk": "Үйрек еті", "calories": 337, "protein": 15.8, "fat": 28.0, "carbs": 0, "category": "meat"},
    {"name_ru": "Баранина", "name_en": "Lamb", "name_uk": "Баранина", "name_kk": "Қой еті", "calories": 203, "protein": 18.0, "fat": 14.0, "carbs": 0, "category": "meat"},
    {"name_ru": "Колбаса варёная", "name_en": "Boiled sausage", "name_uk": "Ковбаса варена", "name_kk": "Пісірілген шұжық", "calories": 220, "protein": 12.0, "fat": 20.0, "carbs": 2.0, "category": "meat"},
    {"name_ru": "Сосиски", "name_en": "Hot dogs", "name_uk": "Сосиски", "name_kk": "Сосискалар", "calories": 256, "protein": 11.0, "fat": 22.0, "carbs": 3.0, "category": "meat"},

    # === МОЛОЧНОЕ ===
    {"name_ru": "Кефир 1%", "name_en": "Kefir 1%", "name_uk": "Кефір 1%", "name_kk": "Кефир 1%", "calories": 40, "protein": 3.0, "fat": 1.0, "carbs": 4.0, "category": "dairy"},
    {"name_ru": "Молоко 2,5%", "name_en": "Milk 2.5%", "name_uk": "Молоко 2,5%", "name_kk": "Сүт 2,5%", "calories": 52, "protein": 2.8, "fat": 2.5, "carbs": 4.7, "category": "dairy"},
    {"name_ru": "Масло сливочное", "name_en": "Butter", "name_uk": "Вершкове масло", "name_kk": "Май", "calories": 748, "protein": 0.8, "fat": 82.5, "carbs": 0.6, "category": "dairy"},
    {"name_ru": "Сметана 15%", "name_en": "Sour cream 15%", "name_uk": "Сметана 15%", "name_kk": "Қаймақ 15%", "calories": 158, "protein": 2.6, "fat": 15.0, "carbs": 3.0, "category": "dairy"},
    {"name_ru": "Сыр Гауда", "name_en": "Gouda cheese", "name_uk": "Сир Гауда", "name_kk": "Гауда ірімшігі", "calories": 356, "protein": 25.0, "fat": 27.4, "carbs": 2.2, "category": "dairy"},
    {"name_ru": "Сыр Моцарелла", "name_en": "Mozzarella", "name_uk": "Моцарела", "name_kk": "Моцарелла", "calories": 280, "protein": 22.0, "fat": 22.4, "carbs": 2.2, "category": "dairy"},
    {"name_ru": "Творог 5%", "name_en": "Cottage cheese 5%", "name_uk": "Творог 5%", "name_kk": "Сүзбе 5%", "calories": 121, "protein": 17.0, "fat": 5.0, "carbs": 3.0, "category": "dairy"},
    {"name_ru": "Творог обезжиренный", "name_en": "Low-fat cottage cheese", "name_uk": "Знежирений творог", "name_kk": "Майсыз сүзбе", "calories": 71, "protein": 16.5, "fat": 0.6, "carbs": 1.3, "category": "dairy"},
    {"name_ru": "Йогурт натуральный", "name_en": "Natural yogurt", "name_uk": "Натуральний йогурт", "name_kk": "Табиғи йогурт", "calories": 68, "protein": 5.0, "fat": 3.2, "carbs": 3.5, "category": "dairy"},
    {"name_ru": "Ряженка", "name_en": "Ryazhenka", "name_uk": "Ряжанка", "name_kk": "Ряженка", "calories": 85, "protein": 3.0, "fat": 4.0, "carbs": 4.2, "category": "dairy"},

    # === ЗЛАКИ ===
    {"name_ru": "Гречка", "name_en": "Buckwheat", "name_uk": "Гречка", "name_kk": "Қарақұмық", "calories": 308, "protein": 12.6, "fat": 3.3, "carbs": 57.1, "category": "grains"},
    {"name_ru": "Киноа", "name_en": "Quinoa", "name_uk": "Кіноа", "name_kk": "Кино", "calories": 368, "protein": 14.1, "fat": 6.1, "carbs": 57.2, "category": "grains"},
    {"name_ru": "Макароны", "name_en": "Pasta", "name_uk": "Макарони", "name_kk": "Макарон", "calories": 371, "protein": 11.0, "fat": 1.5, "carbs": 74.9, "category": "grains"},
    {"name_ru": "Овсянка", "name_en": "Oatmeal", "name_uk": "Вівсянка", "name_kk": "Сұлы", "calories": 389, "protein": 16.9, "fat": 6.9, "carbs": 66.3, "category": "grains"},
    {"name_ru": "Перловка", "name_en": "Barley", "name_uk": "Перловка", "name_kk": "Арпакөже", "calories": 315, "protein": 9.3, "fat": 1.1, "carbs": 67.5, "category": "grains"},
    {"name_ru": "Пшено", "name_en": "Millet", "name_uk": "Пшоно", "name_kk": "Тары", "calories": 378, "protein": 11.5, "fat": 3.3, "carbs": 72.9, "category": "grains"},
    {"name_ru": "Рис белый", "name_en": "White rice", "name_uk": "Білий рис", "name_kk": "Ақ күріш", "calories": 344, "protein": 7.0, "fat": 0.6, "carbs": 78.9, "category": "grains"},
    {"name_ru": "Рис бурый", "name_en": "Brown rice", "name_uk": "Бурий рис", "name_kk": "Қоңыр күріш", "calories": 362, "protein": 7.4, "fat": 1.8, "carbs": 77.2, "category": "grains"},
    {"name_ru": "Хлеб белый", "name_en": "White bread", "name_uk": "Білий хліб", "name_kk": "Ақ нан", "calories": 265, "protein": 7.7, "fat": 3.2, "carbs": 51.0, "category": "grains"},
    {"name_ru": "Хлеб цельнозерновой", "name_en": "Whole grain bread", "name_uk": "Цільнозерновий хліб", "name_kk": "Дәнді нан", "calories": 247, "protein": 9.0, "fat": 3.5, "carbs": 44.0, "category": "grains"},

    # === ОРЕХИ И СЕМЕНА ===
    {"name_ru": "Арахис", "name_en": "Peanuts", "name_uk": "Арахіс", "name_kk": "Жержаңғақ", "calories": 567, "protein": 25.8, "fat": 49.2, "carbs": 16.1, "category": "nuts"},
    {"name_ru": "Грецкий орех", "name_en": "Walnuts", "name_uk": "Волоський горіх", "name_kk": "Жаңғақ", "calories": 654, "protein": 15.2, "fat": 65.2, "carbs": 13.7, "category": "nuts"},
    {"name_ru": "Кешью", "name_en": "Cashews", "name_uk": "Кешью", "name_kk": "Кешью", "calories": 553, "protein": 18.2, "fat": 43.8, "carbs": 30.2, "category": "nuts"},
    {"name_ru": "Кунжут", "name_en": "Sesame", "name_uk": "Кунжут", "name_kk": "Сезам", "calories": 565, "protein": 17.7, "fat": 48.7, "carbs": 23.4, "category": "nuts"},
    {"name_ru": "Лён (семена)", "name_en": "Flax seeds", "name_uk": "Льон (насіння)", "name_kk": "Зығыр тұқымы", "calories": 534, "protein": 18.3, "fat": 42.2, "carbs": 28.9, "category": "nuts"},
    {"name_ru": "Миндаль", "name_en": "Almonds", "name_uk": "Мигдаль", "name_kk": "Бадам", "calories": 579, "protein": 21.2, "fat": 49.9, "carbs": 21.7, "category": "nuts"},
    {"name_ru": "Подсолнечник (семена)", "name_en": "Sunflower seeds", "name_uk": "Соняшник (насіння)", "name_kk": "Күнбағыс тұқымы", "calories": 584, "protein": 20.8, "fat": 51.5, "carbs": 20.0, "category": "nuts"},
    {"name_ru": "Тыква (семена)", "name_en": "Pumpkin seeds", "name_uk": "Гарбуз (насіння)", "name_kk": "Асқабақ тұқымы", "calories": 559, "protein": 30.2, "fat": 49.1, "carbs": 10.7, "category": "nuts"},
    {"name_ru": "Фисташки", "name_en": "Pistachios", "name_uk": "Фісташки", "name_kk": "Бедана жаңғағы", "calories": 562, "protein": 20.2, "fat": 45.4, "carbs": 27.5, "category": "nuts"},
    {"name_ru": "Фундук", "name_en": "Hazelnuts", "name_uk": "Ліщина", "name_kk": "Орман жаңғағы", "calories": 628, "protein": 15.0, "fat": 60.8, "carbs": 16.7, "category": "nuts"},

    # === РЫБА ===
    {"name_ru": "Горбуша", "name_en": "Pink salmon", "name_uk": "Горбуша", "name_kk": "Қызыл балық", "calories": 142, "protein": 21.0, "fat": 6.5, "carbs": 0, "category": "fish"},
    {"name_ru": "Креветки", "name_en": "Shrimp", "name_uk": "Креветки", "name_kk": "Асшаян", "calories": 99, "protein": 18.9, "fat": 2.2, "carbs": 0, "category": "fish"},
    {"name_ru": "Лосось", "name_en": "Salmon", "name_uk": "Лосось", "name_kk": "Лосось", "calories": 208, "protein": 20.0, "fat": 13.0, "carbs": 0, "category": "fish"},
    {"name_ru": "Минтай", "name_en": "Pollock", "name_uk": "Мінтай", "name_kk": "Минтай", "calories": 72, "protein": 15.9, "fat": 0.7, "carbs": 0, "category": "fish"},
    {"name_ru": "Сёмга", "name_en": "Trout", "name_uk": "Сьомга", "name_kk": "Форель", "calories": 219, "protein": 20.8, "fat": 15.1, "carbs": 0, "category": "fish"},
    {"name_ru": "Скумбрия", "name_en": "Mackerel", "name_uk": "Скумбрія", "name_kk": "Скумбрия", "calories": 262, "protein": 18.0, "fat": 13.2, "carbs": 0, "category": "fish"},
    {"name_ru": "Сельдь", "name_en": "Herring", "name_uk": "Оселедець", "name_kk": "Майшабақ", "calories": 217, "protein": 17.7, "fat": 19.5, "carbs": 0, "category": "fish"},
    {"name_ru": "Тунец", "name_en": "Tuna", "name_uk": "Тунець", "name_kk": "Тунец", "calories": 136, "protein": 23.3, "fat": 4.9, "carbs": 0, "category": "fish"},
    {"name_ru": "Треска", "name_en": "Cod", "name_uk": "Тріска", "name_kk": "Треска", "calories": 69, "protein": 16.0, "fat": 0.4, "carbs": 0, "category": "fish"},
    {"name_ru": "Хек", "name_en": "Hake", "name_uk": "Хек", "name_kk": "Хек", "calories": 86, "protein": 16.6, "fat": 2.2, "carbs": 0, "category": "fish"},

    # === СЛАДКОЕ ===
    {"name_ru": "Варенье", "name_en": "Jam", "name_uk": "Варення", "name_kk": "Тосап", "calories": 238, "protein": 0.3, "fat": 0.1, "carbs": 65.0, "category": "sweets"},
    {"name_ru": "Зефир", "name_en": "Marshmallow", "name_uk": "Зефір", "name_kk": "Зефир", "calories": 304, "protein": 0.8, "fat": 0, "carbs": 78.3, "category": "sweets"},
    {"name_ru": "Мёд", "name_en": "Honey", "name_uk": "Мед", "name_kk": "Бал", "calories": 304, "protein": 0.8, "fat": 0, "carbs": 82.4, "category": "sweets"},
    {"name_ru": "Мороженое пломбир", "name_en": "Ice cream", "name_uk": "Морозиво пломбір", "name_kk": "Балмұздақ", "calories": 227, "protein": 3.7, "fat": 12.0, "carbs": 27.7, "category": "sweets"},
    {"name_ru": "Печенье", "name_en": "Cookies", "name_uk": "Печиво", "name_kk": "Печенье", "calories": 424, "protein": 7.5, "fat": 14.8, "carbs": 67.1, "category": "sweets"},
    {"name_ru": "Пирог яблочный", "name_en": "Apple pie", "name_uk": "Яблучний пиріг", "name_kk": "Алмалы пирог", "calories": 265, "protein": 4.0, "fat": 11.0, "carbs": 38.0, "category": "sweets"},
    {"name_ru": "Сахар", "name_en": "Sugar", "name_uk": "Цукор", "name_kk": "Қант", "calories": 387, "protein": 0, "fat": 0, "carbs": 99.9, "category": "sweets"},
    {"name_ru": "Торт бисквитный", "name_en": "Sponge cake", "name_uk": "Бісквітний торт", "name_kk": "Бисквит торты", "calories": 350, "protein": 5.0, "fat": 12.0, "carbs": 58.0, "category": "sweets"},
    {"name_ru": "Шоколад горький", "name_en": "Dark chocolate", "name_uk": "Гіркий шоколад", "name_kk": "Ащы шоколад", "calories": 539, "protein": 5.4, "fat": 35.4, "carbs": 56.9, "category": "sweets"},
    {"name_ru": "Шоколад молочный", "name_en": "Milk chocolate", "name_uk": "Молочний шоколад", "name_kk": "Сүтті шоколад", "calories": 535, "protein": 6.9, "fat": 29.6, "carbs": 59.4, "category": "sweets"},

    # === НАПИТКИ ===
    {"name_ru": "Апельсиновый сок", "name_en": "Orange juice", "name_uk": "Апельсиновий сік", "name_kk": "Апельсин шырыны", "calories": 45, "protein": 0.7, "fat": 0.2, "carbs": 10.4, "category": "drinks"},
    {"name_ru": "Вода", "name_en": "Water", "name_uk": "Вода", "name_kk": "Су", "calories": 0, "protein": 0, "fat": 0, "carbs": 0, "category": "drinks"},
    {"name_ru": "Зелёный чай", "name_en": "Green tea", "name_uk": "Зелений чай", "name_kk": "Жасыл шай", "calories": 1, "protein": 0, "fat": 0, "carbs": 0, "category": "drinks"},
    {"name_ru": "Кефир 1%", "name_en": "Kefir 1%", "name_uk": "Кефір 1%", "name_kk": "Кефир 1%", "calories": 40, "protein": 3.0, "fat": 1.0, "carbs": 4.0, "category": "drinks"},
    {"name_ru": "Кола", "name_en": "Cola", "name_uk": "Кола", "name_kk": "Кола", "calories": 42, "protein": 0, "fat": 0, "carbs": 10.6, "category": "drinks"},
    {"name_ru": "Кофе чёрный", "name_en": "Black coffee", "name_uk": "Чорна кава", "name_kk": "Қара кофе", "calories": 2, "protein": 0.3, "fat": 0, "carbs": 0, "category": "drinks"},
    {"name_ru": "Молоко 2,5% (напиток)", "name_en": "Milk 2.5% (drink)", "name_uk": "Молоко 2,5% (напій)", "name_kk": "Сүт 2,5% (сусын)", "calories": 52, "protein": 2.8, "fat": 2.5, "carbs": 4.7, "category": "drinks"},
    {"name_ru": "Смузи зелёный", "name_en": "Green smoothie", "name_uk": "Зелений смузі", "name_kk": "Жасыл смузи", "calories": 60, "protein": 1.5, "fat": 0.5, "carbs": 14.0, "category": "drinks"},
    {"name_ru": "Томатный сок", "name_en": "Tomato juice", "name_uk": "Томатний сік", "name_kk": "Қызанақ шырыны", "calories": 18, "protein": 0.9, "fat": 0, "carbs": 3.5, "category": "drinks"},
    {"name_ru": "Чёрный чай", "name_en": "Black tea", "name_uk": "Чорний чай", "name_kk": "Қара шай", "calories": 1, "protein": 0.1, "fat": 0, "carbs": 0.3, "category": "drinks"},

    # === ДРУГОЕ ===
    {"name_ru": "Бобы чёрные", "name_en": "Black beans", "name_uk": "Чорні боби", "name_kk": "Қара бұршақ", "calories": 341, "protein": 21.6, "fat": 1.4, "carbs": 62.4, "category": "other"},
    {"name_ru": "Горчица", "name_en": "Mustard", "name_uk": "Гірчиця", "name_kk": "Қышқыл", "calories": 67, "protein": 4.0, "fat": 4.0, "carbs": 5.0, "category": "other"},
    {"name_ru": "Майонез", "name_en": "Mayonnaise", "name_uk": "Майонез", "name_kk": "Майонез", "calories": 680, "protein": 2.8, "fat": 74.0, "carbs": 2.6, "category": "other"},
    {"name_ru": "Маслины", "name_en": "Olives", "name_uk": "Маслини", "name_kk": "Зәйтүн", "calories": 145, "protein": 1.0, "fat": 15.3, "carbs": 3.8, "category": "other"},
    {"name_ru": "Нут", "name_en": "Chickpeas", "name_uk": "Нут", "name_kk": "Бұршақ", "calories": 364, "protein": 19.0, "fat": 6.0, "carbs": 61.0, "category": "other"},
    {"name_ru": "Оливковое масло", "name_en": "Olive oil", "name_uk": "Оливкова олія", "name_kk": "Зәйтүн майы", "calories": 884, "protein": 0, "fat": 100.0, "carbs": 0, "category": "other"},
    {"name_ru": "Яйцо куриное", "name_en": "Chicken egg", "name_uk": "Куряче яйце", "name_kk": "Тауық жұмыртқасы", "calories": 155, "protein": 13.0, "fat": 11.0, "carbs": 1.1, "category": "other"},
    {"name_ru": "Чечевица", "name_en": "Lentils", "name_uk": "Сочевиця", "name_kk": "Жасымық", "calories": 353, "protein": 24.0, "fat": 1.5, "carbs": 60.0, "category": "other"},
    {"name_ru": "Соевый соус", "name_en": "Soy sauce", "name_uk": "Соєвий соус", "name_kk": "Соя соусы", "calories": 53, "protein": 5.6, "fat": 0, "carbs": 4.9, "category": "other"},
    {"name_ru": "Тофу", "name_en": "Tofu", "name_uk": "Тофу", "name_kk": "Тофу", "calories": 76, "protein": 8.0, "fat": 4.8, "carbs": 1.9, "category": "other"},
    # === ГОТОВЫЕ БЛЮДА ===
    {"name_ru": "Борщ", "name_en": "Borscht", "name_uk": "Борщ", "name_kk": "Борщ", "calories": 55, "protein": 2.8, "fat": 2.1, "carbs": 7.2, "category": "other"},
    {"name_ru": "Пельмени", "name_en": "Dumplings", "name_uk": "Пельмені", "name_kk": "Пельмендер", "calories": 275, "protein": 11.0, "fat": 12.0, "carbs": 29.0, "category": "other"},
    {"name_ru": "Вареники с картошкой", "name_en": "Potato dumplings", "name_uk": "Вареники з картоплею", "name_kk": "Картопты вареник", "calories": 190, "protein": 5.0, "fat": 3.5, "carbs": 35.0, "category": "other"},
    {"name_ru": "Вареники с творогом", "name_en": "Cottage cheese dumplings", "name_uk": "Вареники з сиром", "name_kk": "Сүзбелі вареник", "calories": 210, "protein": 9.0, "fat": 5.0, "carbs": 33.0, "category": "other"},
    {"name_ru": "Плов", "name_en": "Pilaf", "name_uk": "Плов", "name_kk": "Палау", "calories": 220, "protein": 8.0, "fat": 9.0, "carbs": 28.0, "category": "other"},
    {"name_ru": "Гречка с курицей", "name_en": "Buckwheat with chicken", "name_uk": "Гречка з куркою", "name_kk": "Тауықты қарақұмық", "calories": 165, "protein": 14.0, "fat": 5.0, "carbs": 18.0, "category": "other"},
    {"name_ru": "Рис с курицей", "name_en": "Rice with chicken", "name_uk": "Рис з куркою", "name_kk": "Тауықты күріш", "calories": 155, "protein": 13.0, "fat": 3.5, "carbs": 20.0, "category": "other"},
    {"name_ru": "Макароны с сыром", "name_en": "Mac and cheese", "name_uk": "Макарони з сиром", "name_kk": "Ірімшікті макарон", "calories": 290, "protein": 10.0, "fat": 12.0, "carbs": 37.0, "category": "other"},
    {"name_ru": "Омлет", "name_en": "Omelette", "name_uk": "Омлет", "name_kk": "Омлет", "calories": 184, "protein": 11.0, "fat": 15.0, "carbs": 2.0, "category": "other"},
    {"name_ru": "Яичница", "name_en": "Fried eggs", "name_uk": "Яєчня", "name_kk": "Қуырылған жұмыртқа", "calories": 192, "protein": 13.0, "fat": 15.0, "carbs": 1.0, "category": "other"},
    {"name_ru": "Блины", "name_en": "Pancakes", "name_uk": "Млинці", "name_kk": "Блин", "calories": 233, "protein": 6.1, "fat": 9.0, "carbs": 33.0, "category": "other"},
    {"name_ru": "Оладьи", "name_en": "Fritters", "name_uk": "Оладки", "name_kk": "Оладья", "calories": 250, "protein": 6.0, "fat": 10.0, "carbs": 34.0, "category": "other"},
    {"name_ru": "Каша овсяная на молоке", "name_en": "Oatmeal with milk", "name_uk": "Вівсяна каша на молоці", "name_kk": "Сүтті сұлы қаша", "calories": 102, "protein": 3.5, "fat": 3.2, "carbs": 15.0, "category": "other"},
    {"name_ru": "Каша гречневая на воде", "name_en": "Buckwheat porridge", "name_uk": "Гречана каша на воді", "name_kk": "Сулы қарақұмық қаша", "calories": 132, "protein": 4.5, "fat": 2.3, "carbs": 25.0, "category": "other"},
    {"name_ru": "Суп куриный", "name_en": "Chicken soup", "name_uk": "Курячий суп", "name_kk": "Тауық сорпасы", "calories": 45, "protein": 4.0, "fat": 1.5, "carbs": 4.0, "category": "other"},
    {"name_ru": "Щи", "name_en": "Shchi cabbage soup", "name_uk": "Щі", "name_kk": "Щи", "calories": 48, "protein": 2.5, "fat": 2.0, "carbs": 5.5, "category": "other"},
    {"name_ru": "Солянка", "name_en": "Solyanka soup", "name_uk": "Солянка", "name_kk": "Солянка", "calories": 68, "protein": 4.5, "fat": 3.5, "carbs": 5.0, "category": "other"},
    {"name_ru": "Окрошка", "name_en": "Okroshka", "name_uk": "Окрошка", "name_kk": "Окрошка", "calories": 42, "protein": 2.5, "fat": 1.5, "carbs": 5.0, "category": "other"},
    {"name_ru": "Котлета куриная", "name_en": "Chicken cutlet", "name_uk": "Куряча котлета", "name_kk": "Тауық котлеті", "calories": 190, "protein": 17.0, "fat": 11.0, "carbs": 6.0, "category": "other"},
    {"name_ru": "Котлета говяжья", "name_en": "Beef cutlet", "name_uk": "Яловича котлета", "name_kk": "Сиыр котлеті", "calories": 235, "protein": 16.0, "fat": 16.0, "carbs": 7.0, "category": "other"},
    {"name_ru": "Тефтели", "name_en": "Meatballs", "name_uk": "Тефтелі", "name_kk": "Тефтель", "calories": 194, "protein": 13.0, "fat": 12.0, "carbs": 8.0, "category": "other"},
    {"name_ru": "Голубцы", "name_en": "Stuffed cabbage rolls", "name_uk": "Голубці", "name_kk": "Голубец", "calories": 160, "protein": 9.0, "fat": 9.0, "carbs": 12.0, "category": "other"},
    {"name_ru": "Пицца Маргарита", "name_en": "Pizza Margherita", "name_uk": "Піца Маргарита", "name_kk": "Маргарита пицца", "calories": 250, "protein": 11.0, "fat": 9.0, "carbs": 32.0, "category": "other"},
    {"name_ru": "Бургер", "name_en": "Burger", "name_uk": "Бургер", "name_kk": "Бургер", "calories": 295, "protein": 15.0, "fat": 14.0, "carbs": 28.0, "category": "other"},
    {"name_ru": "Хот-дог", "name_en": "Hot dog", "name_uk": "Хот-дог", "name_kk": "Хот-дог", "calories": 290, "protein": 11.0, "fat": 16.0, "carbs": 26.0, "category": "other"},
    {"name_ru": "Шаурма", "name_en": "Shawarma", "name_uk": "Шаурма", "name_kk": "Шаурма", "calories": 280, "protein": 13.0, "fat": 14.0, "carbs": 27.0, "category": "other"},
    {"name_ru": "Роллы Филадельфия", "name_en": "Philadelphia rolls", "name_uk": "Роли Філадельфія", "name_kk": "Филадельфия ролл", "calories": 175, "protein": 7.0, "fat": 8.0, "carbs": 19.0, "category": "other"},
    {"name_ru": "Суши с лососем", "name_en": "Salmon sushi", "name_uk": "Суші з лососем", "name_kk": "Лососьді суши", "calories": 140, "protein": 6.5, "fat": 4.5, "carbs": 18.0, "category": "other"},
    {"name_ru": "Греческий салат", "name_en": "Greek salad", "name_uk": "Грецький салат", "name_kk": "Грек салаты", "calories": 95, "protein": 3.5, "fat": 7.0, "carbs": 6.0, "category": "other"},
    {"name_ru": "Салат Цезарь", "name_en": "Caesar salad", "name_uk": "Салат Цезар", "name_kk": "Цезарь салаты", "calories": 170, "protein": 9.0, "fat": 12.0, "carbs": 8.0, "category": "other"},
    {"name_ru": "Оливье", "name_en": "Olivier salad", "name_uk": "Олів'є", "name_kk": "Оливье салаты", "calories": 198, "protein": 6.5, "fat": 14.0, "carbs": 13.0, "category": "other"},
    {"name_ru": "Винегрет", "name_en": "Vinaigrette salad", "name_uk": "Вінегрет", "name_kk": "Винегрет", "calories": 110, "protein": 2.5, "fat": 5.0, "carbs": 15.0, "category": "other"},
    {"name_ru": "Картошка фри", "name_en": "French fries", "name_uk": "Картопля фрі", "name_kk": "Картоп фри", "calories": 312, "protein": 3.4, "fat": 15.0, "carbs": 41.0, "category": "other"},
    {"name_ru": "Картофельное пюре", "name_en": "Mashed potatoes", "name_uk": "Картопляне пюре", "name_kk": "Картоп пюресі", "calories": 105, "protein": 2.5, "fat": 4.0, "carbs": 16.0, "category": "other"},
    {"name_ru": "Жареная картошка", "name_en": "Fried potatoes", "name_uk": "Смажена картопля", "name_kk": "Қуырылған картоп", "calories": 218, "protein": 3.0, "fat": 10.0, "carbs": 29.0, "category": "other"},
    {"name_ru": "Паста Болоньезе", "name_en": "Pasta Bolognese", "name_uk": "Паста Болоньєзе", "name_kk": "Болоньезе паста", "calories": 185, "protein": 10.0, "fat": 7.0, "carbs": 22.0, "category": "other"},
    {"name_ru": "Паста Карбонара", "name_en": "Pasta Carbonara", "name_uk": "Паста Карбонара", "name_kk": "Карбонара паста", "calories": 320, "protein": 13.0, "fat": 16.0, "carbs": 32.0, "category": "other"},
    {"name_ru": "Лазанья", "name_en": "Lasagna", "name_uk": "Лазанья", "name_kk": "Лазанья", "calories": 280, "protein": 14.0, "fat": 13.0, "carbs": 28.0, "category": "other"},
    {"name_ru": "Стейк говяжий", "name_en": "Beef steak", "name_uk": "Яловичий стейк", "name_kk": "Сиыр стейкі", "calories": 271, "protein": 26.0, "fat": 18.0, "carbs": 0, "category": "other"},
    {"name_ru": "Курица гриль", "name_en": "Grilled chicken", "name_uk": "Курка гриль", "name_kk": "Гриль тауық", "calories": 215, "protein": 28.0, "fat": 11.0, "carbs": 0, "category": "other"},
    {"name_ru": "Рыба жареная", "name_en": "Fried fish", "name_uk": "Смажена риба", "name_kk": "Қуырылған балық", "calories": 190, "protein": 18.0, "fat": 11.0, "carbs": 5.0, "category": "other"},
    {"name_ru": "Творожная запеканка", "name_en": "Cottage cheese casserole", "name_uk": "Сирна запіканка", "name_kk": "Сүзбе запеканкасы", "calories": 170, "protein": 12.0, "fat": 6.0, "carbs": 18.0, "category": "other"},
    {"name_ru": "Сырники", "name_en": "Cottage cheese pancakes", "name_uk": "Сирники", "name_kk": "Сырник", "calories": 260, "protein": 14.0, "fat": 10.0, "carbs": 28.0, "category": "other"},
    {"name_ru": "Манная каша", "name_en": "Semolina porridge", "name_uk": "Манна каша", "name_kk": "Манна қаша", "calories": 98, "protein": 3.0, "fat": 2.5, "carbs": 16.5, "category": "other"},
    {"name_ru": "Рисовая каша на молоке", "name_en": "Rice porridge with milk", "name_uk": "Рисова каша на молоці", "name_kk": "Сүтті күріш қаша", "calories": 97, "protein": 3.0, "fat": 2.5, "carbs": 16.0, "category": "other"},
    {"name_ru": "Бефстроганов", "name_en": "Beef Stroganoff", "name_uk": "Бефстроганов", "name_kk": "Бефстроганов", "calories": 198, "protein": 17.0, "fat": 12.0, "carbs": 5.0, "category": "other"},
    {"name_ru": "Харчо", "name_en": "Kharcho soup", "name_uk": "Харчо", "name_kk": "Харчо", "calories": 70, "protein": 4.0, "fat": 3.0, "carbs": 7.0, "category": "other"},
    {"name_ru": "Уха", "name_en": "Fish soup", "name_uk": "Юшка", "name_kk": "Балық сорпасы", "calories": 38, "protein": 4.5, "fat": 1.0, "carbs": 3.0, "category": "other"},
    {"name_ru": "Гуляш", "name_en": "Goulash", "name_uk": "Гуляш", "name_kk": "Гуляш", "calories": 175, "protein": 14.0, "fat": 10.0, "carbs": 7.0, "category": "other"},
    {"name_ru": "Долма", "name_en": "Dolma", "name_uk": "Долма", "name_kk": "Долма", "calories": 155, "protein": 8.0, "fat": 8.0, "carbs": 14.0, "category": "other"},
    {"name_ru": "Манты", "name_en": "Manti", "name_uk": "Манти", "name_kk": "Манты", "calories": 220, "protein": 10.0, "fat": 9.0, "carbs": 26.0, "category": "other"},
    {"name_ru": "Бешбармак", "name_en": "Beshbarmak", "name_uk": "Бешбармак", "name_kk": "Бесбармақ", "calories": 245, "protein": 14.0, "fat": 11.0, "carbs": 24.0, "category": "other"},
    {"name_ru": "Лагман", "name_en": "Laghman", "name_uk": "Лагман", "name_kk": "Лағман", "calories": 195, "protein": 9.0, "fat": 8.0, "carbs": 23.0, "category": "other"},
    {"name_ru": "Чебурек", "name_en": "Cheburek", "name_uk": "Чебурек", "name_kk": "Шебурек", "calories": 320, "protein": 12.0, "fat": 17.0, "carbs": 30.0, "category": "other"},
    {"name_ru": "Беляш", "name_en": "Belyash", "name_uk": "Біляш", "name_kk": "Беляш", "calories": 295, "protein": 11.0, "fat": 15.0, "carbs": 29.0, "category": "other"},
    {"name_ru": "Пирожок с мясом", "name_en": "Meat pie", "name_uk": "Пиріжок з мясом", "name_kk": "Etті пирожок", "calories": 285, "protein": 10.0, "fat": 13.0, "carbs": 32.0, "category": "other"},
    {"name_ru": "Пирожок с капустой", "name_en": "Cabbage pie", "name_uk": "Пиріжок з капустою", "name_kk": "Орамжапырақты пирожок", "calories": 215, "protein": 5.0, "fat": 8.0, "carbs": 31.0, "category": "other"},

    # === ЕЩЁ ФРУКТЫ ===
    {"name_ru": "Айва", "name_en": "Quince", "name_uk": "Айва", "name_kk": "Айва", "calories": 57, "protein": 0.4, "fat": 0.1, "carbs": 15.3, "category": "fruits"},
    {"name_ru": "Алыча", "name_en": "Cherry plum", "name_uk": "Аличя", "name_kk": "Алша", "calories": 34, "protein": 0.2, "fat": 0.1, "carbs": 7.9, "category": "fruits"},
    {"name_ru": "Брусника", "name_en": "Lingonberry", "name_uk": "Брусниця", "name_kk": "Қызылжидек", "calories": 46, "protein": 0.7, "fat": 0.5, "carbs": 8.2, "category": "fruits"},
    {"name_ru": "Голубика", "name_en": "Blueberry wild", "name_uk": "Голубика", "name_kk": "Өрік жидек", "calories": 39, "protein": 1.0, "fat": 0.5, "carbs": 6.6, "category": "fruits"},
    {"name_ru": "Ежевика", "name_en": "Blackberry", "name_uk": "Ожина", "name_kk": "Қара жидек", "calories": 34, "protein": 1.5, "fat": 0.5, "carbs": 4.4, "category": "fruits"},
    {"name_ru": "Инжир", "name_en": "Fig", "name_uk": "Інжир", "name_kk": "Інжір", "calories": 74, "protein": 0.7, "fat": 0.2, "carbs": 19.2, "category": "fruits"},
    {"name_ru": "Крыжовник", "name_en": "Gooseberry", "name_uk": "Аґрус", "name_kk": "Қарақат", "calories": 43, "protein": 0.7, "fat": 0.2, "carbs": 9.1, "category": "fruits"},
    {"name_ru": "Личи", "name_en": "Lychee", "name_uk": "Лічі", "name_kk": "Личи", "calories": 66, "protein": 0.8, "fat": 0.4, "carbs": 16.5, "category": "fruits"},
    {"name_ru": "Маракуйя", "name_en": "Passion fruit", "name_uk": "Маракуя", "name_kk": "Маракуйя", "calories": 97, "protein": 2.2, "fat": 0.7, "carbs": 23.4, "category": "fruits"},
    {"name_ru": "Нектарин", "name_en": "Nectarine", "name_uk": "Нектарин", "name_kk": "Нектарин", "calories": 44, "protein": 1.1, "fat": 0.3, "carbs": 10.6, "category": "fruits"},
    {"name_ru": "Смородина чёрная", "name_en": "Black currant", "name_uk": "Смородина чорна", "name_kk": "Қара қарақат", "calories": 44, "protein": 1.0, "fat": 0.4, "carbs": 7.3, "category": "fruits"},
    {"name_ru": "Черешня", "name_en": "Sweet cherry", "name_uk": "Черешня", "name_kk": "Черешня", "calories": 52, "protein": 1.1, "fat": 0.4, "carbs": 10.6, "category": "fruits"},
    {"name_ru": "Хурма", "name_en": "Persimmon", "name_uk": "Хурма", "name_kk": "Хурма", "calories": 67, "protein": 0.5, "fat": 0.4, "carbs": 16.9, "category": "fruits"},

    # === ЕЩЁ ОВОЩИ ===
    {"name_ru": "Артишок", "name_en": "Artichoke", "name_uk": "Артишок", "name_kk": "Артишок", "calories": 47, "protein": 3.3, "fat": 0.2, "carbs": 10.5, "category": "vegetables"},
    {"name_ru": "Аспарагус", "name_en": "Asparagus", "name_uk": "Спаржа", "name_kk": "Аспарагус", "calories": 20, "protein": 2.2, "fat": 0.1, "carbs": 3.9, "category": "vegetables"},
    {"name_ru": "Батат", "name_en": "Sweet potato", "name_uk": "Батат", "name_kk": "Тәтті картоп", "calories": 86, "protein": 1.6, "fat": 0.1, "carbs": 20.1, "category": "vegetables"},
    {"name_ru": "Брюссельская капуста", "name_en": "Brussels sprouts", "name_uk": "Брюссельська капуста", "name_kk": "Брюссель қырыққабаты", "calories": 43, "protein": 3.4, "fat": 0.3, "carbs": 9.0, "category": "vegetables"},
    {"name_ru": "Имбирь", "name_en": "Ginger", "name_uk": "Імбир", "name_kk": "Зімбір", "calories": 80, "protein": 1.8, "fat": 0.8, "carbs": 17.8, "category": "vegetables"},
    {"name_ru": "Лук-порей", "name_en": "Leek", "name_uk": "Цибуля-порей", "name_kk": "Жасыл пияз", "calories": 61, "protein": 1.5, "fat": 0.3, "carbs": 14.2, "category": "vegetables"},
    {"name_ru": "Пастернак", "name_en": "Parsnip", "name_uk": "Пастернак", "name_kk": "Пастернак", "calories": 75, "protein": 1.2, "fat": 0.3, "carbs": 17.9, "category": "vegetables"},
    {"name_ru": "Репа", "name_en": "Turnip", "name_uk": "Ріпа", "name_kk": "Шалқан", "calories": 28, "protein": 0.9, "fat": 0.1, "carbs": 6.4, "category": "vegetables"},
    {"name_ru": "Руккола", "name_en": "Arugula", "name_uk": "Рукола", "name_kk": "Рукола", "calories": 25, "protein": 2.6, "fat": 0.7, "carbs": 3.7, "category": "vegetables"},
    {"name_ru": "Топинамбур", "name_en": "Jerusalem artichoke", "name_uk": "Топінамбур", "name_kk": "Топинамбур", "calories": 73, "protein": 2.1, "fat": 0.1, "carbs": 17.4, "category": "vegetables"},

    # === ЕЩЁ МОЛОЧНОЕ ===
    {"name_ru": "Айран", "name_en": "Ayran", "name_uk": "Айран", "name_kk": "Айран", "calories": 27, "protein": 1.1, "fat": 1.5, "carbs": 2.2, "category": "dairy"},
    {"name_ru": "Брынза", "name_en": "Bryndza cheese", "name_uk": "Бринза", "name_kk": "Брынза", "calories": 260, "protein": 17.9, "fat": 20.1, "carbs": 0.0, "category": "dairy"},
    {"name_ru": "Пармезан", "name_en": "Parmesan", "name_uk": "Пармезан", "name_kk": "Пармезан", "calories": 392, "protein": 35.8, "fat": 25.8, "carbs": 3.2, "category": "dairy"},
    {"name_ru": "Рикотта", "name_en": "Ricotta", "name_uk": "Рикота", "name_kk": "Рикотта", "calories": 174, "protein": 11.3, "fat": 13.0, "carbs": 3.0, "category": "dairy"},
    {"name_ru": "Сливки 20%", "name_en": "Cream 20%", "name_uk": "Вершки 20%", "name_kk": "Қаймақ 20%", "calories": 205, "protein": 2.8, "fat": 20.0, "carbs": 3.7, "category": "dairy"},
    {"name_ru": "Сыр Фета", "name_en": "Feta cheese", "name_uk": "Сир Фета", "name_kk": "Фета ірімшігі", "calories": 264, "protein": 14.2, "fat": 21.3, "carbs": 4.1, "category": "dairy"},
    {"name_ru": "Сыр Чеддер", "name_en": "Cheddar cheese", "name_uk": "Сир Чеддер", "name_kk": "Чеддер ірімшігі", "calories": 402, "protein": 23.0, "fat": 33.1, "carbs": 1.3, "category": "dairy"},
    {"name_ru": "Сыр Российский", "name_en": "Russian cheese", "name_uk": "Сир Російський", "name_kk": "Орыс ірімшігі", "calories": 364, "protein": 23.2, "fat": 29.5, "carbs": 0.3, "category": "dairy"},

    # === ЕЩЁ ЗЛАКИ И ХЛЕБ ===
    {"name_ru": "Батон нарезной", "name_en": "Sliced loaf", "name_uk": "Батон нарізний", "name_kk": "Нарезной батон", "calories": 264, "protein": 7.9, "fat": 3.2, "carbs": 51.0, "category": "grains"},
    {"name_ru": "Булочка для бургера", "name_en": "Burger bun", "name_uk": "Булочка для бургера", "name_kk": "Бургер булочкасы", "calories": 280, "protein": 8.0, "fat": 4.5, "carbs": 53.0, "category": "grains"},
    {"name_ru": "Кукурузные хлопья", "name_en": "Corn flakes", "name_uk": "Кукурудзяні пластівці", "name_kk": "Жүгері үлпектері", "calories": 357, "protein": 7.0, "fat": 0.9, "carbs": 83.6, "category": "grains"},
    {"name_ru": "Мюсли", "name_en": "Muesli", "name_uk": "Мюслі", "name_kk": "Мюсли", "calories": 352, "protein": 10.4, "fat": 6.4, "carbs": 65.2, "category": "grains"},
    {"name_ru": "Гранола", "name_en": "Granola", "name_uk": "Гранола", "name_kk": "Гранола", "calories": 471, "protein": 10.0, "fat": 20.0, "carbs": 64.0, "category": "grains"},
    {"name_ru": "Лаваш", "name_en": "Lavash", "name_uk": "Лаваш", "name_kk": "Лаваш", "calories": 277, "protein": 9.1, "fat": 1.1, "carbs": 57.1, "category": "grains"},
    {"name_ru": "Хлебцы рисовые", "name_en": "Rice cakes", "name_uk": "Рисові хлібці", "name_kk": "Күріш нан", "calories": 390, "protein": 8.0, "fat": 3.5, "carbs": 81.0, "category": "grains"},
    {"name_ru": "Ячневая каша", "name_en": "Barley porridge", "name_uk": "Ячна каша", "name_kk": "Арпа қашасы", "calories": 324, "protein": 10.4, "fat": 1.3, "carbs": 66.3, "category": "grains"},

    # === ЕЩЁ МЯСО И КОЛБАСЫ ===
    {"name_ru": "Бекон", "name_en": "Bacon", "name_uk": "Бекон", "name_kk": "Бекон", "calories": 541, "protein": 37.0, "fat": 45.0, "carbs": 0, "category": "meat"},
    {"name_ru": "Ветчина", "name_en": "Ham", "name_uk": "Шинка", "name_kk": "Ветчина", "calories": 278, "protein": 22.6, "fat": 20.9, "carbs": 0, "category": "meat"},
    {"name_ru": "Говядина тушёная", "name_en": "Stewed beef", "name_uk": "Тушкована яловичина", "name_kk": "Тұшіп пісірілген сиыр", "calories": 214, "protein": 22.0, "fat": 14.0, "carbs": 0, "category": "meat"},
    {"name_ru": "Кролик", "name_en": "Rabbit", "name_uk": "Кролик", "name_kk": "Қоян еті", "calories": 183, "protein": 21.2, "fat": 11.0, "carbs": 0, "category": "meat"},
    {"name_ru": "Куриная печень", "name_en": "Chicken liver", "name_uk": "Куряча печінка", "name_kk": "Тауық бауыры", "calories": 140, "protein": 20.4, "fat": 5.9, "carbs": 1.0, "category": "meat"},
    {"name_ru": "Печень говяжья", "name_en": "Beef liver", "name_uk": "Яловича печінка", "name_kk": "Сиыр бауыры", "calories": 125, "protein": 17.9, "fat": 3.7, "carbs": 5.3, "category": "meat"},
    {"name_ru": "Салями", "name_en": "Salami", "name_uk": "Салямі", "name_kk": "Салями", "calories": 407, "protein": 22.6, "fat": 35.5, "carbs": 1.2, "category": "meat"},

    # === ЕЩЁ РЫБА ===
    {"name_ru": "Анчоусы", "name_en": "Anchovies", "name_uk": "Анчоуси", "name_kk": "Анчоус", "calories": 131, "protein": 20.4, "fat": 4.8, "carbs": 0, "category": "fish"},
    {"name_ru": "Икра красная", "name_en": "Red caviar", "name_uk": "Червона ікра", "name_kk": "Қызыл уылдырық", "calories": 251, "protein": 31.5, "fat": 13.2, "carbs": 0, "category": "fish"},
    {"name_ru": "Кальмар", "name_en": "Squid", "name_uk": "Кальмар", "name_kk": "Кальмар", "calories": 92, "protein": 18.0, "fat": 2.2, "carbs": 2.0, "category": "fish"},
    {"name_ru": "Карп", "name_en": "Carp", "name_uk": "Короп", "name_kk": "Тұқы", "calories": 112, "protein": 16.0, "fat": 5.3, "carbs": 0, "category": "fish"},
    {"name_ru": "Мидии", "name_en": "Mussels", "name_uk": "Мідії", "name_kk": "Мидия", "calories": 77, "protein": 11.5, "fat": 2.0, "carbs": 3.3, "category": "fish"},
    {"name_ru": "Минога", "name_en": "Lamprey", "name_uk": "Мінога", "name_kk": "Минога", "calories": 166, "protein": 14.7, "fat": 11.9, "carbs": 0, "category": "fish"},
    {"name_ru": "Осьминог", "name_en": "Octopus", "name_uk": "Восьминіг", "name_kk": "Сегізаяқ", "calories": 82, "protein": 14.9, "fat": 1.0, "carbs": 2.2, "category": "fish"},
    {"name_ru": "Палтус", "name_en": "Halibut", "name_uk": "Палтус", "name_kk": "Палтус", "calories": 103, "protein": 18.9, "fat": 3.0, "carbs": 0, "category": "fish"},
    {"name_ru": "Устрицы", "name_en": "Oysters", "name_uk": "Устриці", "name_kk": "Устрица", "calories": 72, "protein": 9.0, "fat": 2.0, "carbs": 4.5, "category": "fish"},

    # === ЕЩЁ НАПИТКИ ===
    {"name_ru": "Какао на молоке", "name_en": "Cocoa with milk", "name_uk": "Какао на молоці", "name_kk": "Сүтті какао", "calories": 97, "protein": 4.3, "fat": 3.9, "carbs": 12.5, "category": "drinks"},
    {"name_ru": "Капучино", "name_en": "Cappuccino", "name_uk": "Капучино", "name_kk": "Капучино", "calories": 74, "protein": 3.8, "fat": 3.5, "carbs": 6.5, "category": "drinks"},
    {"name_ru": "Кофе латте", "name_en": "Latte", "name_uk": "Кава латте", "name_kk": "Латте", "calories": 61, "protein": 3.2, "fat": 2.8, "carbs": 5.5, "category": "drinks"},
    {"name_ru": "Кумыс", "name_en": "Kumis", "name_uk": "Кумис", "name_kk": "Қымыз", "calories": 50, "protein": 2.1, "fat": 1.9, "carbs": 5.0, "category": "drinks"},
    {"name_ru": "Лимонад", "name_en": "Lemonade", "name_uk": "Лимонад", "name_kk": "Лимонад", "calories": 38, "protein": 0, "fat": 0, "carbs": 9.8, "category": "drinks"},
    {"name_ru": "Морс", "name_en": "Berry drink", "name_uk": "Морс", "name_kk": "Морс", "calories": 48, "protein": 0.1, "fat": 0, "carbs": 12.5, "category": "drinks"},
    {"name_ru": "Протеиновый коктейль", "name_en": "Protein shake", "name_uk": "Протеїновий коктейль", "name_kk": "Протеин коктейлі", "calories": 110, "protein": 20.0, "fat": 2.0, "carbs": 6.0, "category": "drinks"},
    {"name_ru": "Шиповник (отвар)", "name_en": "Rosehip tea", "name_uk": "Шипшина (відвар)", "name_kk": "Итмұрын сусыны", "calories": 19, "protein": 0.1, "fat": 0, "carbs": 4.5, "category": "drinks"},
    {"name_ru": "Энергетик", "name_en": "Energy drink", "name_uk": "Енергетик", "name_kk": "Энергетик", "calories": 45, "protein": 0, "fat": 0, "carbs": 11.3, "category": "drinks"},

    # === ЕЩЁ СЛАДКОЕ ===
    {"name_ru": "Вафли", "name_en": "Waffles", "name_uk": "Вафлі", "name_kk": "Вафли", "calories": 350, "protein": 3.2, "fat": 11.0, "carbs": 62.1, "category": "sweets"},
    {"name_ru": "Карамель", "name_en": "Caramel", "name_uk": "Карамель", "name_kk": "Карамель", "calories": 382, "protein": 0, "fat": 0, "carbs": 95.5, "category": "sweets"},
    {"name_ru": "Мармелад", "name_en": "Marmalade", "name_uk": "Мармелад", "name_kk": "Мармелад", "calories": 293, "protein": 0.1, "fat": 0.1, "carbs": 77.7, "category": "sweets"},
    {"name_ru": "Нутелла", "name_en": "Nutella", "name_uk": "Нутелла", "name_kk": "Нутелла", "calories": 539, "protein": 6.3, "fat": 30.9, "carbs": 57.5, "category": "sweets"},
    {"name_ru": "Пастила", "name_en": "Pastila", "name_uk": "Пастила", "name_kk": "Пастила", "calories": 324, "protein": 0.5, "fat": 0, "carbs": 80.4, "category": "sweets"},
    {"name_ru": "Халва", "name_en": "Halva", "name_uk": "Халва", "name_kk": "Халуа", "calories": 516, "protein": 12.7, "fat": 29.7, "carbs": 54.0, "category": "sweets"},
    {"name_ru": "Чак-чак", "name_en": "Chak-chak", "name_uk": "Чак-чак", "name_kk": "Шақ-шақ", "calories": 469, "protein": 7.5, "fat": 22.0, "carbs": 62.0, "category": "sweets"},
    {"name_ru": "Эклер", "name_en": "Eclair", "name_uk": "Еклер", "name_kk": "Эклер", "calories": 330, "protein": 6.0, "fat": 18.0, "carbs": 36.0, "category": "sweets"},

    # === ЕЩЁ ДРУГОЕ ===
    {"name_ru": "Арахисовая паста", "name_en": "Peanut butter", "name_uk": "Арахісова паста", "name_kk": "Жержаңғақ пастасы", "calories": 588, "protein": 25.1, "fat": 50.4, "carbs": 20.1, "category": "other"},
    {"name_ru": "Горчица", "name_en": "Mustard", "name_uk": "Гірчиця", "name_kk": "Қышқыл", "calories": 67, "protein": 4.0, "fat": 4.0, "carbs": 5.0, "category": "other"},
    {"name_ru": "Кетчуп", "name_en": "Ketchup", "name_uk": "Кетчуп", "name_kk": "Кетчуп", "calories": 93, "protein": 1.8, "fat": 0.1, "carbs": 22.2, "category": "other"},
    {"name_ru": "Протеин (порошок)", "name_en": "Protein powder", "name_uk": "Протеїн (порошок)", "name_kk": "Протеин (ұнтақ)", "calories": 370, "protein": 75.0, "fat": 5.0, "carbs": 10.0, "category": "other"},
    {"name_ru": "Уксус яблочный", "name_en": "Apple cider vinegar", "name_uk": "Яблучний оцет", "name_kk": "Алма сіркесі", "calories": 22, "protein": 0, "fat": 0, "carbs": 0.9, "category": "other"},
    {"name_ru": "Фасоль красная", "name_en": "Red kidney beans", "name_uk": "Червона квасоля", "name_kk": "Қызыл бұршақ", "calories": 333, "protein": 21.0, "fat": 2.0, "carbs": 54.5, "category": "other"},
    {"name_ru": "Хумус", "name_en": "Hummus", "name_uk": "Хумус", "name_kk": "Хумус", "calories": 166, "protein": 7.9, "fat": 9.6, "carbs": 14.3, "category": "other"},
    # === МЯСО РАЗНЫМИ СПОСОБАМИ ПРИГОТОВЛЕНИЯ ===
    {"name_ru": "Говядина варёная", "name_en": "Boiled beef", "name_uk": "Яловичина варена", "name_kk": "Пісірілген сиыр", "calories": 153, "protein": 23.0, "fat": 6.0, "carbs": 0, "category": "meat"},
    {"name_ru": "Говядина жареная", "name_en": "Fried beef", "name_uk": "Смажена яловичина", "name_kk": "Қуырылған сиыр", "calories": 195, "protein": 22.0, "fat": 12.0, "carbs": 0, "category": "meat"},
    {"name_ru": "Говядина запечённая", "name_en": "Baked beef", "name_uk": "Запечена яловичина", "name_kk": "Пештегі сиыр", "calories": 177, "protein": 25.0, "fat": 8.5, "carbs": 0, "category": "meat"},
    {"name_ru": "Говядина тушёная", "name_en": "Stewed beef", "name_uk": "Тушкована яловичина", "name_kk": "Тұшіп пісірілген сиыр", "calories": 165, "protein": 21.0, "fat": 8.0, "carbs": 2.0, "category": "meat"},
    {"name_ru": "Говядина на гриле", "name_en": "Grilled beef", "name_uk": "Яловичина на грилі", "name_kk": "Гриль сиыр", "calories": 200, "protein": 26.0, "fat": 10.0, "carbs": 0, "category": "meat"},
    {"name_ru": "Свинина варёная", "name_en": "Boiled pork", "name_uk": "Варена свинина", "name_kk": "Пісірілген шошқа", "calories": 255, "protein": 20.0, "fat": 19.0, "carbs": 0, "category": "meat"},
    {"name_ru": "Свинина жареная", "name_en": "Fried pork", "name_uk": "Смажена свинина", "name_kk": "Қуырылған шошқа", "calories": 280, "protein": 18.0, "fat": 23.0, "carbs": 0, "category": "meat"},
    {"name_ru": "Свинина запечённая", "name_en": "Baked pork", "name_uk": "Запечена свинина", "name_kk": "Пештегі шошқа", "calories": 260, "protein": 19.0, "fat": 20.0, "carbs": 0, "category": "meat"},
    {"name_ru": "Свинина на гриле", "name_en": "Grilled pork", "name_uk": "Свинина на грилі", "name_kk": "Гриль шошқа", "calories": 270, "protein": 20.0, "fat": 21.0, "carbs": 0, "category": "meat"},
    {"name_ru": "Курица варёная", "name_en": "Boiled chicken", "name_uk": "Варена курка", "name_kk": "Пісірілген тауық", "calories": 135, "protein": 25.0, "fat": 3.5, "carbs": 0, "category": "meat"},
    {"name_ru": "Курица жареная", "name_en": "Fried chicken", "name_uk": "Смажена курка", "name_kk": "Қуырылған тауық", "calories": 210, "protein": 23.0, "fat": 13.0, "carbs": 2.0, "category": "meat"},
    {"name_ru": "Курица запечённая", "name_en": "Baked chicken", "name_uk": "Запечена курка", "name_kk": "Пештегі тауық", "calories": 185, "protein": 26.0, "fat": 9.0, "carbs": 0, "category": "meat"},
    {"name_ru": "Курица на гриле", "name_en": "Grilled chicken", "name_uk": "Курка на грилі", "name_kk": "Гриль тауық", "calories": 195, "protein": 27.0, "fat": 9.5, "carbs": 0, "category": "meat"},
    {"name_ru": "Курица копчёная", "name_en": "Smoked chicken", "name_uk": "Копчена курка", "name_kk": "Ысталған тауық", "calories": 184, "protein": 27.5, "fat": 8.2, "carbs": 0, "category": "meat"},
    {"name_ru": "Баранина варёная", "name_en": "Boiled lamb", "name_uk": "Варена баранина", "name_kk": "Пісірілген қой", "calories": 191, "protein": 22.0, "fat": 11.0, "carbs": 0, "category": "meat"},
    {"name_ru": "Баранина жареная", "name_en": "Fried lamb", "name_uk": "Смажена баранина", "name_kk": "Қуырылған қой", "calories": 225, "protein": 20.0, "fat": 16.0, "carbs": 0, "category": "meat"},
    {"name_ru": "Баранина на гриле", "name_en": "Grilled lamb", "name_uk": "Баранина на грилі", "name_kk": "Гриль қой", "calories": 218, "protein": 21.0, "fat": 14.5, "carbs": 0, "category": "meat"},
    {"name_ru": "Шашлык из свинины", "name_en": "Pork shashlik", "name_uk": "Шашлик зі свинини", "name_kk": "Шошқа шашлығы", "calories": 280, "protein": 18.0, "fat": 22.0, "carbs": 2.0, "category": "meat"},
    {"name_ru": "Шашлык из говядины", "name_en": "Beef shashlik", "name_uk": "Шашлик з яловичини", "name_kk": "Сиыр шашлығы", "calories": 220, "protein": 24.0, "fat": 13.0, "carbs": 2.0, "category": "meat"},
    {"name_ru": "Шашлык из курицы", "name_en": "Chicken shashlik", "name_uk": "Шашлик з курки", "name_kk": "Тауық шашлығы", "calories": 175, "protein": 25.0, "fat": 8.0, "carbs": 3.0, "category": "meat"},
    {"name_ru": "Шашлык из баранины", "name_en": "Lamb shashlik", "name_uk": "Шашлик з баранини", "name_kk": "Қой шашлығы", "calories": 230, "protein": 20.0, "fat": 16.0, "carbs": 2.0, "category": "meat"},
    {"name_ru": "Отбивная свиная", "name_en": "Pork chop", "name_uk": "Свиняча відбивна", "name_kk": "Шошқа котлеті", "calories": 265, "protein": 19.0, "fat": 20.0, "carbs": 4.0, "category": "meat"},
    {"name_ru": "Отбивная куриная", "name_en": "Chicken chop", "name_uk": "Куряча відбивна", "name_kk": "Тауық котлеті", "calories": 195, "protein": 22.0, "fat": 10.0, "carbs": 5.0, "category": "meat"},
    {"name_ru": "Стейк из лосося", "name_en": "Salmon steak", "name_uk": "Стейк з лосося", "name_kk": "Лосось стейкі", "calories": 208, "protein": 20.0, "fat": 13.0, "carbs": 0, "category": "fish"},
    {"name_ru": "Рыба запечённая", "name_en": "Baked fish", "name_uk": "Запечена риба", "name_kk": "Пештегі балық", "calories": 120, "protein": 19.0, "fat": 4.5, "carbs": 0, "category": "fish"},
    {"name_ru": "Рыба на гриле", "name_en": "Grilled fish", "name_uk": "Риба на грилі", "name_kk": "Гриль балық", "calories": 130, "protein": 20.0, "fat": 5.0, "carbs": 0, "category": "fish"},
    {"name_ru": "Рыба варёная", "name_en": "Boiled fish", "name_uk": "Варена риба", "name_kk": "Пісірілген балық", "calories": 100, "protein": 18.0, "fat": 3.0, "carbs": 0, "category": "fish"},
    {"name_ru": "Рыба копчёная", "name_en": "Smoked fish", "name_uk": "Копчена риба", "name_kk": "Ысталған балық", "calories": 172, "protein": 22.0, "fat": 9.0, "carbs": 0, "category": "fish"},
]
